---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.4
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    worker:
      config:
        core:
          sources: ["pci", "system", "usb", "kernel"]
        sources:
          usb:
            deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
          pci:
            deviceClassWhitelist: ["02", 0200", "0207", "03", "0300", "0302"]
            deviceLabelFields: ["vendor", "device"]
            vendorLabelMapping:
              8086: "intel"
              10de: "nvidia"
          system:
            attributeWhitelist:
              - "architecture"
          kernel:
            attributeMapping:
              - name: "Kernel version"
                attribute: "version"
    prometheus:
      enable: true
