---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1csku9hc05cs2f4hp89w079czpdzpx89mj7zq23e9k9nscxxcfausx2yhzl"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1csku9hc05cs2f4hp89w079czpdzpx89mj7zq23e9k9nscxxcfausx2yhzl"
