apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: cnpg-postgresql
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: trixie
    images.cnpg.io/date: "20260427"
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.9-system-trixie
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
