apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: postgres
type: Opaque
data:
    aws-access-key-id: ENC[AES256_GCM,data:VqyRCitl1QmJKCEPzQ+8FmYu6M8BxIYUctfZ/4RY5ocSSt4t+01ZCNH8DoE=,iv:i0CDP8GirIygUJ20x7J/B1jOkGW38iUTNDddAtV8cxg=,tag:aMwPdu0lYlNhzmVOsleF8Q==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:mxwjB/RyUenawY9M1uCYcMQIPzdnhDnjvSMcQOJx8zayvekfHGKH8fpVTts31YqOjw6KWdTrWoNnYKhX30o6ERi4E7rDOMCZZyJ7s7RxxvxFkfw9bFrefQ==,iv:SKMV20lxnKDKOJsKn2vM/I8jrhOGe5Y+lvdRt0NFQUE=,tag:QWuHoSw2liCrCEq5TTKCtw==,type:str]
    username: ENC[AES256_GCM,data:WQlxnueRxY+fM259,iv:QXByrJG4lEDeQO8LkigDkwJFTEY19OHk1AvjbOSXUhE=,tag:f6K2/WQIkTyN1yogvX1Gig==,type:str]
    password: ENC[AES256_GCM,data:UE2fGsqCtIzgkha6,iv:eWwzxewqhmsb1eU0zGF0ER1NcfSMV+E+zjUhgU4uFYc=,tag:DevASyooqRWLETpzZZSYGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb2I3NnJQODdPaWgyblli
            MFQzQU53aEtWbkIvbnZsUW1WQVlYdmg3V0NRCmdhbFdGTEVSMWlzREhaK0FzYmp0
            b2xhalZNL2xoT29DTmlOdi85S0t3a3MKLS0tIE9PMW03U2duN3NUL3AvTXZ0NGxS
            TXZUWlU4S2N3OUIyQVpyUGcyU3o5SXMKXzl71Q9c1qZNkkY5nBDATExHQnkust08
            HwgNSoJ5jRPyA8b+CRcGpJLEPJzY43yE1pOJHawSCdv0JsPQfVt+HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T19:19:06Z"
    mac: ENC[AES256_GCM,data:ABlCXYwYO/aJ+KQfWDrGU7cvX20geUsubbI9D0RHowN1Uy76sFpN9dMXcVCIZIXI+IOD3Dlzryp6fA4NyFBjUWWjoFXQO9DbYWK9PMavv/XfKgRAqFFzfuxvxe1pTmSwh5yAsukyHMp9S3eweNLCniIDIoPT9cOrIukEzbOjkjk=,iv:AvB3quoheacIQCPnYih20U7Zfa4Y1zj9wAPDm5mLLNs=,tag:ujZ+mrZnfAgWU9GUlwBFBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
