apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  namespace: postgres
type: Opaque
data:
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ouXW1Q8nH+JBbCBT,iv:SrSQN23NMaysp1F2CAalnAuC6ywZYfv0a+G2I8JVExM=,tag:qIbP+j2P1Fhv3rPvTUGBiw==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:McdskLuJK6t/59Cb,iv:gUckvWM2bFGgTR5e9gIoFxjZfy1fhRnqercu+pvwhrc=,tag:ylG4y4EHtUYI5A8NuqJrTA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:WEbP0ltO51u/kslwcZcPGXuKg/ZYeAXURaVnMIGkmQjjcgDxtrOQ5qFx8oQ=,iv:VWtW4APyQYogomHBJEe3PHpyduwRSqIdhS5mBWPbgcU=,tag:dNG02iW0ktKjJk6G/hNh1g==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:WdqUgMs9wccAuSNBwFjAM7yykCh7aYgzLfOEmXdPsVgQlilD7IgxFEudpxfBYpniEilA9RJdfQlhPLFvPBWxwsv3U/oBU4f7x6F4SGHI3kAK2DIsgdiNKg==,iv:/0eZnP97mRG+p5yDdZI+Kx78MM90UB+82XWwBHQmV1k=,tag:dGJdjMdDkcp+7WmroqOT0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZTdUdjZPR2R6WnVJSTFk
        eGpWZWxUWHUxYkx1YUNpZjBNYnpSaWJzSEJvCkFRN200a3cvKzVZak81SnBoYlI1
        OGdQMFZRN2laTlNJek9LRW5SaXhreXMKLS0tIDlOSTRRaXdVR256KzltSDJIdnhq
        cldIbWQrSHE5elFBbFRPTWNRdlZpRDgK6jDcS7vWIonGejElKs6woRRWXJaBwYCe
        BfjaVoVjk/JbxrQNADTgQlVk5IdVNSVfC9/FPgBHp12Z7EROfdoWiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-20T17:32:41Z"
  mac: ENC[AES256_GCM,data:LOpEQiTpFzJwb9XUh0UAT/e7GOJGr63E0nmkl6JTmzc42M+ImhTTBsfl55cxnbqfXtSm7AQWRBRwyYnKcLnUQa5e8Qm7EuU84bYnutb6EYkzL1Q/hPQHNFJ7XOp9wvuFzcrDaTx4tJwtBo/0o+DuNpPT4CyjVqhoywXI2fTsVBE=,iv:QqlgIepgjz8SDAmrqOLcA2RywI6iFdTnfsu6aMudpfY=,tag:dXKv1YfnvgfpQp0YLUDXTA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
