# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-r2-token
  namespace: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-api-key-secret
