---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cnpg-secrets.sops.yaml
  - ./cluster.yaml
  - ./scheduledbackup.yaml
  # - ./prometheusrule.yaml
