---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: &clusterName cnpg-postgres
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: *clusterName
