# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MuKQC7B3dmttwAjIWPy2eICFYiRe,iv:frnaWJKqEp+PihdfciGP5RBFBWxFqfQf/s3Z4Mb7YK4=,tag:VJcnRQoe/LAfO0KSejlMtw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dxto/o5HVCdHqnSuB6u+o5k1ZILi2OlKxhX4ILH/NgW2MjAuFg==,iv:2PoVQsIcCZHzeruUidhQKH+1PPkTyZykKnc+5FnssLo=,tag:xh1Gr7fL3g/R4fM6x6F7Fw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:hUeG5GTC6uzFGyS0eoTcxg==,iv:B4cs61aLo0gR2XyQj+tXdQQiiu1BQBLryxAvvVTj3dw=,tag:zYXeMEsCfwO/uOWBH1X8Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubGYrNDdyZU9MdlExYmpo
            UG8rUmhNZDJ6eE4xQVFRc05rQ0VkUkdtSGlnCmwrdmJZaENQWnVKZGhIblU0YjFY
            TlF5NzM4TWZ6VUhMMVIvYWs4eGM2clkKLS0tIEdwOTZoa0hRcnRGSXNhWW9SaEJn
            ZmwyeittWE9UOHU0bmFFUmNXcW5hVVEK2Zpic9QGaLdIG7+MvV2yDRrXeULwRt9+
            af2xkKoeOsR01cWpPXDcXtaimbug5/p9c2wqm9dzbl2oyCiMQoGkXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T05:50:19Z"
    mac: ENC[AES256_GCM,data:W3Kd7ssftMksgqXLymei3MoRYW3xQUCvNLdrzcED0/h3LwzzWmSDjgQhJNauj6E//7XeYU+JI151SYqqd4dnxQjOVw80naZzU22Lj0CT0Jpv1RVzFvF2xa/D7A73sj3UTrC/MCFXWQoHSIS6YT0cjk3f98WatPiJXKJyYQMJeF8=,iv:0wl7xz0AbyORugFIP+VuLoPwexoiJ8IMQd6BbrHJM4s=,tag:eJjDOJTkkBiaCJyEaRnByw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
