apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - jetstack.yaml
  - sealed-secrets.yaml
  - metallb.yaml
  - podinfo.yaml
  - ingress-nginx.yaml
  - bitnami.yaml
  - 1password.yaml
