---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg-charts.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia.yaml
  - ./openebs.yaml
  - ./open-telemetry.yaml
  - ./stakater.yaml
