---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: grafana-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        admin-user: "{{ index . \"admin-user\" }}"
        admin-password: "{{ index . \"admin-password\" }}"
  dataFrom:
    - extract:
        key: grafana-admin
