apiVersion: v1
kind: Secret
metadata:
    name: sab-env
    namespace: media
type: Opaque
data:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:69HngPDQsXek/KdtDiFaqRfGj8Sbv8wUWKTaPr+jPwUMYlNv5lJ9ILIO+hM=,iv:AvMFi+F5F/ybNmi3jOSOxBD3i/6r4EOCRHxD3JvTf/Y=,tag:eThBzS7bHYdf6K8zvLsnzA==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:FZoKEDyLKwMyHKtBvirxO0qbLlH8SDwfPYLaP/t53CfzJc9xuqacmnvLai8=,iv:ooPhegp1rF4s6RO5+77Klzh70brah3Ep0a5+uvw7428=,tag:mTH0zqa6BMdmaTLw016vUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaVd4dmQrQlFKQjNwM3JW
            a0MvZWVTdmQ4UXppVGZpUlBKMUhaWC8yemdFCkFydWFGY2lZdmNhVlJRdzd6T3pP
            aGtDZ01rNWF0QUYwMm91Y1daQzVvR2cKLS0tIElJNFIvRENhbFJad2ZYcExuVFMx
            dDFpTkZ5RG9TTU1qTFYzZ2hSVTVqL1kK/IiN2iWZkKe212ERoR+TXNrCgHhWwB8H
            o5TIBqHjtRwtH8PCWZLtNMQyR2LNx7R1L+fCLh5JiFK7id61Ko5dLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T02:29:54Z"
    mac: ENC[AES256_GCM,data:h+zBhg7kYqy7ZGyyZ5c9nzgK+2yELDXNXX1HPq4kryTu1Kqy2w8FRZYyJHh30H+ZoWyWo8Va9LcES7jsVypBI5WYNzAiW+jXhNddkknhKdNqSSkfycKN2cupHIUqg9VsVNKgZ7eFdZ2+jQqsFBm2WdDVnOoEH6zK4LqRj4uoXl0=,iv:2e5d2WBxfRvnZ8Y9iG8DwBgllqzq5HWhlLnL07Fb4k8=,tag:rv9sqmnqhy64fS+raBCwRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
