---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nvidia-gpu-device
spec:
  rules:
    - # GeForce GTX 1650 Mobile / Max-Q
      name: nvidia.gpu
      labels:
        nvidia.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["10de"] }
            device: { op: In, value: ["1f91"] }
