---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nzbget-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-volume
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: media-volume
