apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:yl9JhgVT++Oy0H2xN9Sklv49xSbO7EhKO1dtglYDj4kqtI/o,iv:G1ibpERyUSjUwzEQ/62xY03nq/6XV4XUKNosm8iVo/w=,tag:h0tL4puf0NIaUqPSCqdMBg==,type:str]
    credentials.json: ENC[AES256_GCM,data:/TieikNQBPlG03TduPAkXCQEgawVZ2XTnDjrD7BT7U+8xfvS2/VY6xeLbPZcVqwlYVx8YWVwx6jh/oAhf9Yb6S31kffsVf5U9gAaslUhu57DTrRMkii1aXblWXIJca1HxyDTM974/21hcGUxmQWqOzi0LJQMcMonjAHAsqCqaDw5kHj181SGrrZcV3Z1+8w93YXY8XkPg0gsf5JWcKIMfEq9eGVDbAleSJpKotfXjg==,iv:3nCrm7LtUUYC72tN8bP63zdMgPk5TWSL50hq7QDL50c=,tag:Iup2XfX/wmDI2L6UyPKlsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdUlYaExvN3JmK0JEVVU2
            V1gxVHRlbDJyQllLRWdsTHdWWTZRS3FxMkFjCkF6WEprZ2pma1I4Slo4MDNVZVF2
            RUtBd3JJSXNzNmVjNHl3UDBHaGNYYmMKLS0tIGlMS3ZlVnFjeTBtcGlyNEhybjE3
            QVpSZzB4aTEwbnVMblMycGgwMFRmOEEKvk39XXGp6zBeeFSN1aMvljZMyJ1vaOYT
            baPsiQpSjJvdE5RKN217uIT64FMc/13eJRa7/zHopicAPrcaefW7pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T20:16:25Z"
    mac: ENC[AES256_GCM,data:htGh8HTNTEzzVX81tH3VIofIOlUMBJT5bENmhg3D9Iqdb+9HhAZyXrV9cc5oCebnTEEn+7J0iLd9LhcnRp9JzM0BotArMj+t9gTbJJO5qHdBwjl9lpXa0IvYHAnPi0J4ZhZdblAiRNFtyPV1yGbR1kD3KZJ92/2Z7TAmRHI1O6E=,iv:76vesl8rEAtBV+nToKwskWuDHPpEW9cwx4mQYwbM5gY=,tag:y/30T56gi+zgIzPTRjew8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
