apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XS82blfnKN1CQjnH7ddpj8HN1uBEtSG6zGz5QAxkus7OR3se,iv:JfUiUTy+/URhRkHGBLEeyw4kSKaEQ8xFbSp4N+fNAEQ=,tag:f/5dC1/PtdG1EocKmXVOFg==,type:str]
    credentials.json: ENC[AES256_GCM,data:OOvhrg9zXtHIio2lW8MYpNNlYERsYg5EC3unJ9yZC12Eqxqvjl7LGDCQslRDr3HqyVcJXJ48EJKA64ENz0gNEHn+3RnTA9Mabh9G33rNKhmiByasrsXLBIiS1J2wh7hcPuOzDv3Uh+mOzrU2dhjnWmDe6Xzf4qeG0Mf2CS3B42P+FXv8gCUZO8DrHFrd3hYlM2Pv8+2pfOZ7WzDfgvMWtKfl3usw023tM3ZbkiOo1g==,iv:LNH9xS4TOaKfZhFwN68MhNRBlyFfkqbHft8Sq2WPG6w=,tag:P4hFt0IfU1o9oNQeeA/PKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z3loUVQ0NDVQNGMrSFpk
            UTJtNFBIaE5SSjZuTG1QWnNlVWsxTmpoTVZrCmc2OVJ5UDZzU2w0OE15c2lYcUxT
            Z0ZFaEpaSE9pbHJJeHUvazkvNnIzajQKLS0tIC9hK05hNnhpWXk5UUdOQi9pclhy
            Vko3SGZsTSszcUZ4YXVMMjFjc08xR2sKF45aPOAuF5SvQnNJZvYU2CeUm4o2yUOy
            tY2m/++0S78G5ZOx9/ZHKzHXjNExbAm2QDAcjdY8kyZF0G9xwM6ofA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T01:57:25Z"
    mac: ENC[AES256_GCM,data:K6b12QQBis2TWhaY179jUrhwTJtWH9oFR210ZhdHIHl86wYmvfqA1Iy1ehDRysMrqb8ABEhokfQ7s8c53clhXxY3BIldVRSAOPTocmYI4B0SaaYIT2CJAgmjH0ffL0DVT7/CzArqjDDKUuVgTZebVLyWUmrktm7IZFYg5wDbB1o=,iv:3zAuvTuIA9VWbGKqs9Gr/jB9eJxRfDseclKlHIcDHvw=,tag:PZjb1KiBuH9LrEX0GR+lEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
