apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Oo+fi51zs8Ctg14PKd4jgCeNpvnVNTKoLXiOS+mZ/EoPV2Cr,iv:/+xEESvRhoJWSFG2o9h85te7f5iOzLTqQGg0ZQIVsHg=,tag:VEeuNBqcK3Y0VyLyChud+w==,type:str]
    credentials.json: ENC[AES256_GCM,data:hoeJzBm4C/1VOyDaybFSCw7GvPAWqHoMJ7U1vFFFFltJdUshZvWNEwd5uQJ0/Mbw6x7soXSg3XzEd2TDyEHPjwnX6lm2+6vYYlrBANns0w5oQwaIc9lJnyGGCDQcrcuQ9fykIfH1B2YH2Bzwl34I+wDrFT3EbdFwaQToDRdIhIGJqVf8DFc5JPflwi6AhkQCYlkIGipavyZkifq+rizuOBAHp4S1hwYymdezxls9SA==,iv:FEpRbN/AfPWka6S7SvIQhIDK0fH95+T7iszCiqgDrLU=,tag:yH3EEpgTCA2vbmX3XMwy3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOUxWSEdlYjVlbzNQWlEy
            aUNNRk9aUWhXK3E2c1lwNi9Ma0c3MVBYWWxNCk5PbjU1Y1lXNkZtM1Rod1lwenVk
            bTZtbXFub3BrNjNpUUFmWFRYREJOQ28KLS0tIDdLV1ZiQ1Q4VzZDOGxERnhMSHhN
            dENmUm1kc2hOREl3dVYvUzNhLzluQVUKRBuuX8MfA92mtnF7QV5TkmMay3h4dUE8
            3Mou2h1TXjB15v1c0HAbXY/7F5VxTH09E/bom30UJjko9McJ4mvuVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T16:52:43Z"
    mac: ENC[AES256_GCM,data:Mm+wbEL5tP7p40nFxQ+ksHw739cMuo9gTKlx8n/1MdkHMaMI5G22Ix1ChlXgjwd/niGBjzPcQfeR92njhh5hVzPQXPYPGVOOxnVsT5If8hfbtWICBhwwyMpnHAeXB0+oEyxwHn53V1xJ2L03XIjL9WiX8oFsBJL8Y97In2gS6ms=,iv:kEk7n82lRZEITdDUyJFeBNskHcSKuYJ/x2NtIWBltRg=,tag:7aNGDTzgcUFaOZs6d3PMxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
