apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:4oJ8FAUixkcM0i8qB0R5pHGFxWA7sWP68tdY8aGkPkWIrbkc,iv:GfAtjrjz5y70o87gswE8qqGGUs6zrTvTI4mG57X1AgM=,tag:wLO+/mAHudazAbWQAFgZ8w==,type:str]
    credentials.json: ENC[AES256_GCM,data:mbLKPU/9fsZjzlHoJjn/2NLOZuIVR8BUZh7PYxjZo9dACK7InVlzr/FvxrPdZbqabrqOQcvVOSGaDvHM0olWh4jep7YilrlEfO6qABDOsX/98WQzAAOgGpJ2Tm1cQh9UfYRmQwAbmdKdkppEg7xgFSPv4EDk8C8oLTaTPWC0Dgvth2N2XBHFND1eoeRGjN4AktPQoaf81fZNKxjOBV05rvrpLpVIcS+Bsd8+V8DNsg==,iv:tXeD0ipsuOY/w4yez6OmZmUWoEKG1KvfjiNiGBEVNnQ=,tag:23oeMVbgE0H/4gT3JdcNrw==,type:str]
sops:
    age:
        - recipient: age13tgynpy3lm785sydz78hxx5dlqp85g25an4tmekx5l99fdzzns0qd89t25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTnJDTUNUazFORDFMMkp5
            bkxZQ2FIQ2RXcnQvUWtxRmYwMFo1Vy9QRDJNCkZvVVlCNy9PNGgydVFZdVNrVHAw
            dmRyVzhHV1AxeGRqWVV4NUp5a1RBYlUKLS0tIFAxZjdxMFpoY0MxMlN5ZHQ3V2JI
            RUZCdk5qMjZSbWt3bDcwS0czeTV5TG8KoiPhUE8scV++QAY+94Dk15wjA15zC87s
            szqwZ6E9cT4P/PDjvSo0Rpf2hOdjajm40YZTwYDMSireoFJLav0RpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T01:58:22Z"
    mac: ENC[AES256_GCM,data:hkJI+cxjysR7rPB+5Kn7/oNiUakRa3nFc/vJscD/1zYboc7NapCWQWF4aqQ+uLTXDSncRh/+nreFeyMbcA86Xq2omcXJdLZ1XUS15MY2Y0jOj9O/P8EmMZZAq9zQrIza0uBho+5moKkVzjpvJMHt4W8pSqYAd1JbD+NQ4sNRww0=,iv:LF4xma2jDHKOCkxMToMHMcoF2QVcVTdnW3e4FNvm+s8=,tag:TFGFLxuuPSeFFrtztEzrnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
