apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hyZp2lF8wIFxY2OQuaC2UwCEaF+PkOxb9gVZd2s4miD9GGNs,iv:wRS8V1f0TIxJS8JTxcybh2kU2ZANgx+LcvwkjX8x7Fw=,tag:sCtXdNWBPgQUilXWFTzScA==,type:str]
    credentials.json: ENC[AES256_GCM,data:GafyGVhdRC/9nz+c/3xNk5QwGyNWX4qfQvCsYIkBz3ctIV00sgKjTsFd104/tY6/t1luz1HJZGL/Md/SWb6EBVANtrayxuHf3WikLp/O1ec3R56zML4NtuxmSKzpfATuYUA7/4q6pdwWEJ2WETINRrYyVP81LrAWvxOBbx6WQj/BEoVil8K8gO3s8Fr/aGjjAgerzpUEyVeDv3L+mc3UXxm5m7Ajds4jQYQXbKU0kw==,iv:FdXguEDmlOdbJc7Fft2NjHW4JyiavmDHYXVhjB5qDK8=,tag:QXRo76P5Ye4P+9ymkRf3/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU1lKdjhieGtERnAvR0tu
            VDdYRGtRcU1nbVJWblAyay9Nc0NnNitvUHpNCnFTT2tkOTNKTFJSZUdUUHY0Y01P
            VU5jK2NjZ2kyc09JUitKaFF5UTNJT0kKLS0tIGNkanVVdzRYOU84UlE0Q3Nxa3lS
            M1MrNnBad09hajIwbk5wc1VhYjN5WE0Kuql7s6qJQGNU7aITSSLl0cv729i04Ci4
            ucwcTtWqf8cMS9uBJ4b0fq11+SYp/Q7ivA5aBg2xh57+Qktb4oznRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T16:01:27Z"
    mac: ENC[AES256_GCM,data:hrlYaC31Nhtppli0ZLXMd/RNiPwX1MssF+lU78P0f10B/bzrcuBsI6xbAsDQNqxrvieeit0/MkUUz7FavIR6F8Yxbfat6UTQuOhQudSHNQ+6HwWppnmuXkpt9pr4e5rFLxbo2n79vOMls8Pj4+XwafFJXO+cKZKJWNmVVWr2iVo=,iv:ya/RFcAGUKs6tQMM663dZE/VqmKnHj6oBWdKtoiu0yo=,tag:zIkyVLM3UPNoimd4i7zVfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
