apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ACxu7nRLZ+vNOBuuDk8J3TOWICf53qlRN81UUIP1TOpP/ULd,iv:fY0wNjC0KO/YMOpM550ffhpo5btDtA+0F6rkKZLMgvg=,tag:JlPDsNRPsoHkzKNfpS4zsA==,type:str]
    credentials.json: ENC[AES256_GCM,data:u8D+c6Mo4tgIC2gzZxcf1T2siJ7JCAJyULy1c4j5iQ4QKWnYgqAidSWSTIqKI0ARSku6AP0gauYFBzZz3bq59bYoep2JJeKtjyFtA499UbvlcbxbrnWNXvnvmSfv9SNw+d4cWk+c3l2c264Ji4mzyq0bOxGm+/JkGfSX6ELowlQUJAHWRSHyczfpbVCyrlTCLtx/LcTYqBvSIMIkdaw2fNfgRWB985Io9HZrNTHuVQ==,iv:9t9UZPrt/F/KO3ReEHkVgU+hKkmowN7qCpvvxJVWrHs=,tag:3EN/LLveBjrnj/3kp1H0WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TXpQUTdhS3Q5YkxHZDI1
            M1UwVktodE9pZHhFZ1pMeFRkUlF3OUNvUDFJClZYNjhtMUQ3TTlna3h3Y2lIcHox
            S1ZFVTBsTmg3NjhXVnF6SndpRmR0MU0KLS0tIGV6blhNemxVZDYrZHllaUNGS1dV
            SEVoYys5R2NsTjhUd0NybWttM2JIdjQKC5CufRC2EI2SDTt30XgQfWNpo9Raxl0Y
            oPH9iOfW0G5gkPd165fbsw7q6Su/ldIdx0f1W902wmfCTWtkLiobxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T17:03:14Z"
    mac: ENC[AES256_GCM,data:mMNn75yLwzRrx9lE6+ZPyrEISIX7fw5MEvaGILrLKapjYCsHbjz0+13vrLyJzWwSI/JjSKdChw/syeo7OiMqHuNwrnNrJazDi8NtmbQvzFOLnV7PTjK6ZvGeqOl/aKZVMOM2dcqZEo7xE1XyM7clbfWSWtQf9VyYw9VDs9NhkNM=,iv:j2y94k+uYtXO2RjAQ7TT8lSQx+THB8KCE7tlmVA7WFA=,tag:IpnMiE/V4e4TnrWOfbbDSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
