apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacDEwL2M2b2s4UEt3OFls
            R0ZCcGJxMjc3KzRwSXIvWndSYmgzUFl4bTM0CmNuNG5mUlVpR3dSNWpWaldwRGJt
            QmN2aUQ4NGZXWkc0eklFTW9vRU5zN2cKLS0tIDFYM050dm1uYmQ1YmtJRE5ZRFNF
            eVJJVGtieURlS1RtcmR6dU5MU3U4RGcKfBS7Z306gTCy2nkBsw1HlsdiRajetpHX
            1gELni3VQOx1EQTzkK1Exgf4eWQbwk84isSkbRyNAwmTAEd9OjXXjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T23:30:08Z"
    mac: ENC[AES256_GCM,data:DeUzPK4H4wnztUfOhW3LAQE8j3jRcEqXLa9vxPF/dVjARtCkSWYLjPgfYM1zBcDJmWMj5YLSxJw0uAVW7Gzyr2xkZQfgkHeBenzJu9drqeKUtQqMwiNSwJFzyNF5WqGFqWwvQgxpA8H3Gul30/m/Mueod9y2iZaw1xN7nqYH6Tc=,iv:Mw5XAPs0JkEzXVN8yU3ksTslozCgInd26968+MCStuo=,tag:KMrmCaV7bPhl9lDfGVeUAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
