---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: gpu-system
    - name: csi-driver-nfs
      namespace: storage
    - name: nvidia-device-plugin
      namespace: gpu-system
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/jellyfin
              tag: 10.9.11
              pullPolicy: IfNotPresent
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_PublishedServerUrl: https://{{ .Release.Name }}.${SECRET_DOMAIN}
              NVIDIA_VISIBLE_DEVICES: "all"
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              runAsUser: 0
            resources:
              requests:
                gpu.intel.com/i915: 1
                nvidia.com/gpu: 1
                cpu: 100m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                nvidia.com/gpu: 1
                memory: 4Gi
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
            nvidia.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 0
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
            secretName: "{{ .Release.Name }}-tls"
    persistence:
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      tv:
        enabled: true
        type: hostPath
        hostPath: /mnt/tv
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/movies
      config:
        enabled: true
        type: hostPath
        hostPath: /mnt/jellyfin
