---
k3s_cluster:
  children:
    master:
      hosts:
        pik8s01.nhudson.dev:
          ansible_host: 192.168.6.50
          k3s_control_node: true
    workers:
      hosts:
        pik8s02.nhudson.dev:
          ansible_host: 192.168.6.51
          k3s_control_node: false
        pik8s03.nhudson.dev:
          ansible_host: 192.168.6.52
          k3s_control_node: false
        thrawn.nhudson.dev:
          ansible_host: 192.168.6.53
          k3s_control_node: false
          k3s_nvidia: true
          node-label: "nvidia.com/gpu=true"
