---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
