# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:fbhUeN46mzEuQtPNAg3RAjiWdbOh,iv:Mczu7eyaxz1YUFmbZN/Qj9gBv+I7as6Jugf5pKjx2Gk=,tag:nNSDBJQ4LJCeBK6SKgGsXQ==,type:str]
    api-key: ENC[AES256_GCM,data:7FNRNBzitvj3TTHsff2kkL4s3ExVABS6yTieZeU1RRukTe4oEA==,iv:KRxrdP9rtDu/QxlQ6Y2COFcA0Dr2lG+AIxO7V95c4gs=,tag:c7kWcXanoQzr04MbP4DygQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bWdNeFBRUldtT0t6WmZt
            UEtJR2pvcmxzZTZnUVRzdW5kTFdPTzNtUm1JCmlYckFieGFUalVnS1ArRkhMMUNV
            bG1iN2tNbHlpdjBKTEVBVXI3cDMwSTgKLS0tIGo4Vi9DM29sU1lGSzJJeXNNRk83
            dkV6WHA1K0laKytFZDdobDZUNzBrODgK1dOOtrzeYb5ibzEDXfl4opCMJtFSEln6
            3CSZ4lEogOxSyhSWtU0/ZzPvroEsJk1GcJCWz7nqqB9m3hwvjxOS0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T05:50:19Z"
    mac: ENC[AES256_GCM,data:hWm7WT35LmjXZy4GDbutV85zPrg0Isur5ui/C6JS/9XS2d50jJjofCr/YXFlGvBBYNDITaLeuVBP06UURkinSZHjokWGjM8izL6Yav7eZ6j5Qk9VQDPhob+htD6hq098P/mni4xKdPHzW407GJEkVvWYOq0sWZQLtK0kf6BYSSk=,iv:MBmljVYauBX6ArxKy1Gs9WQudZ+ojqcp8f8DtiG55Dk=,tag:uQDrLPufwzlwaLefTdFy8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
