# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:QIv7QmIdfl3/PtE=,iv:htpw7+sA3x7AaarGHRbN/rd+a7ro0YA/BcPs/JbUles=,tag:FAay8zt2tZHsTk8LPIIWZQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:N1QpaVJb6VOU/6M+/EicQD/anyRe,iv:7oPz+PFuN8jEkeRXwuK4nPGeWRiW53eDrBqNFpuf9wc=,tag:GBwFRkKpiMgKEb5tAKDbGg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1k5t6Uif4ctFbomDFFYvTV3nFvp8DD0GUAXcF/B4TbAoH56W,iv:4xLl3KsNyWv3iDZg/ftd1DQFAU+ZqEzTVSLcaQTIe1c=,tag:j4k5oZoGJ88rYpi6/HQ34Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML3pLWUt2MnVzNytRcU5q
            WVlwYmoyL0dPM1pZY2ZYR0MxQjNWQ0F5bFFRCkhQTmJSSG5TaEtuenVkeU5IeXly
            ME9GZ25FdzZ2Y3NWTURRT0h4WnlxT2cKLS0tIFNjeU0rK3VGYVgxMkRPMGp1aUsz
            aDVEM3lTRlZBcmFVTlA2VGl3R0dOQkEKSV0M6OrmHa0a17lmoIhE9WWwmPkeI6Tv
            +XQxPfpMqnaVhUEwcZru8tZvWnVPqb5+24QFaTgXpgmVLUfhYdkOdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T17:35:07Z"
    mac: ENC[AES256_GCM,data:KFJTI3ti/C65JYx10/pS7zmnNoCnYHy91UIMlW2EIfvEs8i82E/GB9nEGk/dh4vAZ/JdjmFzLWSqJ7ULOvhLuyCyKEaLAbldUuqFhvOzcmiPGe7/1foZ74nEJvjuzRFghnocPxVWgc5/fX3xdVhcvgn3hHuPmmnlVaHqLW6IWIw=,iv:8upvjqhezBTrLHDd4pLNL5T2ilHq7hdVITbAbSuhMgU=,tag:YJhdEbDT4GI01CCG0LaucQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
