# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9RWLLHFDuk7LK5w=,iv:kFIhMAwQF+Wj0OsaTvM2Or8/tsHv02nln4pEfWEGvHo=,tag:oAJ2Dze+OwVhnpNbxEv6Xg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VEdO1UY3IB3RCOlzojE+156RJSC7,iv:Z2P+0O65iphO9/AbJwmf/AWFAd9v1lSLpsSjHJ4HRGM=,tag:zJ5b8PP88kwUk2fIiFbnuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWnZhdE0wb3d2c0RTdGZR
            Z21PL2xBOHo0cXB4VlpSaU9uRjREaDBhd0hZClVaTFN4K255RnR3c0x5WXZ4b29o
            Qm9rWVdPa1NZdG5LNndhTHVrVkl1R2MKLS0tIEVCSk1jUWFNd0hPSWdNc2s4UkJ0
            NkFYSysrOS9xRjQwQlhJT2lCemVTbDQKYAgdQs3PUr8Wpp24OkG0Y0Kkk/xbLpGD
            52VEM6xVIv9k64wPqdPPtpWPT+ttr/83LCam4y0784hkdp8qfgcKAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T05:50:19Z"
    mac: ENC[AES256_GCM,data:OwNOWteXOa0wS3d+rf7Sq+XZS/nzmibv3gE2RydFu/v71cqNDdd1fjv3jKhWxt0G7GxJ2tUq5j8RXVDYg6O9ZXQN8ftZHcQIgVTi6lUPbC+UDlRHuO/A4kVy8fRR8/X4VcTZdeook6hvcblMUzgp8U1LFcyYABxCJA40P+LT5Pc=,iv:e9AZ18Kef51DtWICaP4tyUJEpErqW/Dypr2nHdEdRlk=,tag:AHpF5T2IS2Boqjm2K3vMHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
