# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bhhs3922J2r+LQc=,iv:nqvZcjFHClTJGbcqXDlJ8ukHv5W3dIlznvEEa2Mdu4I=,tag:7SG9W0DrID3cPMsx1+Xz1Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+Mn6qcoLy/BPCvf/878q/1q2ZS2m,iv:d98htv87PwBBdCNaJ/WGp/Af+Nq0VE+AvDJhaqGMBVQ=,tag:df7jhNRKMb2mZ92vi56S4g==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:H8EKSMhBqPA+UA4FRdKgPyZBvElQO8ZINxWF+Iw0nu8gEKWM,iv:NDVcLYSU+TRnAAx69IpK31r7jgdE01lfQ/sKhDD1U38=,tag:gCP+e1Fsaa5/3rboczUvMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSjlEdXdoT1Y3dS8yM3Ey
            RExjSWVaS3hONEYrWUlVYmhVcDFFd1hRMXdJCjc0SEJGWXRvQW9ueWFiQkEyTGRr
            cExBTlU1YmY4c0xhZFlpME96ZGk2a3MKLS0tIFBmbGZRZURhd3FUckRtZjBFV1py
            dDBmT05sSzZpVGNpb3F2Z3k0WUNPM1kKxCNumxIDH/5jDqyZPI3HPALQDJixsA+l
            VF+Z9GVPXDb4oCtxnp+BE4kZOZX9ZMBBV6RY5qemYS6dQH9dxIcTpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T17:58:53Z"
    mac: ENC[AES256_GCM,data:gkh2g9BnaPgM1XgflCYj+7v8bNOTTWo56bT4b+wf42TlNoLCsJHZOY2VzX2smZWNdJTFEjRbgwnl4ZYF60fKR7jHnIFxZryRxPZEimB6Qfe9tJmfmaeLM9HubiZTNtpbDSIEP0OqWH59mF+uFDYLIRef4PEEYgpHlGSRpeGjcxA=,iv:0nDLUl9JZzrCY+lORKTYDZ+cwt5s1eBaHefAYJ5KjYk=,tag:gmi4vQphqaXXVs7FnQfU1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
