apiVersion: v1
kind: Secret
metadata:
    name: grafana-env-secret
    namespace: observability
type: Opaque
data:
    GF_DATABASE_HOST: ENC[AES256_GCM,data:XgQ/PMwerEGM4JJTfEcW0oygVDhHstHf9Z3gTonNEIXdoD5y8lNgDHsKTH8ZpvJxCaDVn4TcwqA=,iv:9ccohX972/FEVqH/ocU7al0HdOHytgzH3WtMxNw/ntg=,tag:MRJTmp3WLlB5/Zw1tYB4TQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:MNTQZ6wfrbtXCKTE,iv:but3aEvG70C5eU3TCJZLtwapWzxaLqMU4N1A92fcEps=,tag:fUCbUSrWbRddE2XOLb+Opw==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:JMUpp1NYWNC/WwUO,iv:3W3DcAir6TPnPBm4r1KVARG1yuIgETXaJYU9GGplmHU=,tag:vLtun1Z9S208Z9HqLH8dxg==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:J7P2jjAFq8QwQV85,iv:8IWyVc3d0LVWYqLwCBLNQOc7GXVTvCF4rVZhr8gwwO0=,tag:14TDNNcv+x49YtR3if1soA==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:EpV/GVIJ6FminPlo,iv:5JDI8sS9Lkk0R1dMx9ophZ/M2kHbiga+kHnVDlfTM4w=,tag:m4pH5jIUHVyp+bBhCn/LrA==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:hdX9IJ5l5f28WXMB,iv:dP4gsiqEEcOSAX2Hw/v0PT6UMTFis1iKhveftsC4cjc=,tag:Tz/IkALd7dJRgqctwiHxUw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:G5Lo0cuAd50WckPJ,iv:qwYjv242O0FdL/pp8uW1ScUc3tIRPTY04g3/hTdo9rs=,tag:YV+3qUO88mXaLAz7d8CxJQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xyGUdJB6TXBOPQ/EhRypZT/dqiQMdeq0QvwmaB+D5uvi6ntB8Vk9x/snIJgmBp9ksyPBng==,iv:YR53BzbKGgSUDeU5Yjru8s2wTZyFxRHUhKBeAA+37BA=,tag:1Qa+QUpdL8rRjqHrOw13fQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:f/vfP/UcIPEOZ3Gs,iv:sNjwZgHamSjYrnUY73JcJ71DM/7tfcD434nDix3emU8=,tag:NY1NBONP/VecgFuEyer0Fg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0m0zO34ZQpzx64C0,iv:wRCVnNZ6itqA7CostbOG0pAZwVWSFCeRfK2cXTYH5pM=,tag:hn02EruL2RaSepjqsVYHwg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:5LzAVY4AeUKna33K,iv:p1vt33tfzAatU1H7TnPREuG85L3Rt6ogAk8KbTEF1xw=,tag:yDK0/frXB1SaekRXpDxd5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEF6MlVwZDRxREllNTBj
            NytaN09qeTByWFRjMlRaeHdNZ1RvclRiR1VVCmd1aFYrQXIybG9JZ3JKSkNrMlpU
            Rnh0dDVwMTA2cHpockhMK1lUanNERFEKLS0tIDUySzlLMTJWd0hSSmFjVFVkWk5o
            aXlnS3J2U29zemdla3V3QnZjVzJmajAKmW9OBxXJJr4UKd/bwNKjQwFnGGKAFI7D
            V9d7N71arTusT3NkC0FSfnAsiilL/Lz/GxiYrkUK9pqd1QUos6Lo+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:25:38Z"
    mac: ENC[AES256_GCM,data:/iokNKubNeJW3S7X/O0A+uE8+8zI8zTbXfg9ByYrS0Fey1cJxCqj+pPBC75743hXDtwlBIm5bRk4r1LZIpz+JSsPi8lxYhDp+dmyUHX+vtPLGcGlJjH/a007v38gPGCoKwqIzVyNuleyoxSbbWmWDG/+O0H9s3cyOWvUov8dVr8=,iv:4yaWZxy7zYNCt0Sh44sHugjjXdHM8RbROvhGVtWLUEE=,tag:pl0rZu3e4DQRwPOdHyVSyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
