apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
data:
    admin-password: ENC[AES256_GCM,data:qgCNwXUxqzE=,iv:uSX7Jjl1gApoJUWHuE8WUoykZtUilqwR32qCwcdpq4I=,tag:EohD2HblwUJUF0rcp5v81g==,type:str]
    admin-user: ENC[AES256_GCM,data:75D63t7+zwE=,iv:3uF+Mz2z4PRIY+KhgA9wRPNQW10rPTyOGlB8S40g4HU=,tag:DOkqHDFvVhcEjkv2pjeQdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N2NIUVNncjdBNVpJS0NV
            ek5DRlVNMmlaZHJrT0tKU3R2SHgzOU15M3hFCmZFL2xhYXJ2Y2JKaFd1NHRkc1Rl
            YmFsRjhJV1c1WURtQVc2WlovV2REOE0KLS0tIGswZ1V6M2NvekhXL0hsb3k5eGlE
            Q2p0UzRYdThlM2ltTXhWOVlQWUZoeEEKkv87grVVic1x2Pf+CK05O3gbna20EWLa
            IO1GbWUtXqOagVHDkRYmYd/cfPgESFxC+96Tfn2HJ2On/EeaQbnxoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:15:59Z"
    mac: ENC[AES256_GCM,data:IfysQQNCedHzDNE1lqze/VbK1JyR3Z97HOzonibP6ogoXmWMPWWWO5mUblsx5i+yAZOdOtNwOusvTufeygeuXBQ2aGMGsEn2ic0c6gMNyhoErPUZ9qgGCBjGQS9ceIg12WBZlKUnwTCoa6b6FUePvlsgKDWnfkd+D3hMtHit55c=,iv:sZEv5+xvlo3RB3zvoBUNI/ksHo311ppCsdrytTNmkH8=,tag:roWgtcPGiuAwtw78G8GNsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
