apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:qPb6yvjfvVQ=,iv:fGBMtLziiGY3I0vjPDpHf3Ci7s0FYmmVUxol7Zv/MjU=,tag:f58EdgSZxJGUKWinAWAhNg==,type:str]
    admin-user: ENC[AES256_GCM,data:hV0eZ2VZdW4=,iv:MQnoFzA091x9AH1LckPiETvyanbk6PWNqOICCUxlNSo=,tag:qry9PNqqRaB4RIO4jCn8MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHak9QaUxMSEtydG5lWnNO
            bms2RWpDVE9vdjg3b1BIS3Y1U2FXUTdqbUhRCm14U3g5YWI0ZzJ3ak1yejJVcWZn
            Q1FYZ1Vjc05DbEFJLzNBZGprK0xrM2sKLS0tIFRyZDZoaTZld0ZQRjZTbDVWaFND
            M1JhV2ExRmJqSmpHNTRtTFU5K210Z28KHmP7xUayYQsrR/xzf187sFeDvILHsFoy
            Vqkjj4U0xni30Govqya9trVZSOM4YhHkmSreAANevIygG25fC1CNpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T18:08:11Z"
    mac: ENC[AES256_GCM,data:0hxjHZChji641LBKcjJ9E4fo8F9ltykwdOyKyN2cRkK7JZW+YPR7IK/TwwrDFKHyulakIoN6Usw5D6g+cxk/UZODUCQ/msqY5Q8Hj0civtv6Xs+Odz6u3LdPk9VMgL8gxZoxRFPGLy/1qiX9NO85jnN22WeXbXcvUYn49OZv/Rs=,iv:4OpuYUgpQdp7PjwDMexNJeZbSDQSw1KYsMD7RFDbuhQ=,tag:5jAtbsZ2kBDDJbZBdcADIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
