apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:J33SIoKkELU=,iv:nHweZumCZbK6RQNcI73fG7F5uqUFmXwt5wpIkS7gQnI=,tag:xqWYwqWvqRtSxb5pCMc5Hw==,type:str]
    admin-user: ENC[AES256_GCM,data:7EY2olgnpYk=,iv:rwecaVxVpBtB5+wkbNUE6qGZw/ytQcmpr+p9VSN5lKA=,tag:qMZ5LSBqvrw+k4UGtpKQAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcEthRy9DRGk1dXFyeHB2
            UDhSM3BuTENDMjFrSE95MkJtYXUwZHNQSDBVCld1OWlPVTJTdElDc1FScWVnamxF
            MnRqYWR2a2dkMmttTGhEK3poQm5YR0EKLS0tIExSRFd2WElkSDJXVjFUdHdIK2NJ
            dmJVTjMvWmJuUmdnSmFNbE0yYi90WVUK9LZZMiwKISVCqhsf7HcaIcR/Dm7/gch5
            rwxD0TArJeGOlkiDv3ySjbYqV4CjLMHwzu/JDckknHS9HR7svrLTXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T20:24:22Z"
    mac: ENC[AES256_GCM,data:GBka00cXcXXD9CBCX4ph53CiA61ZGNiZNg9kd0PLJ8hXiBQYfHOSDXiFViayKE/texwN2f7LP/st0fwCVWQZuLMb+hxuhXUhh30Vg9fGAm9PZXS5yPuLQeEvghXf8Z53MZyHbL6UH+/C78WLck3gz417c4TnAFt8WqVAYup170o=,iv:JExO8InzThieE0YjOfIS1HTW9CFcbP9owHrxd/UBUS8=,tag:X8nMQpDaDrQawL0uiV3+pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
