apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:CBavNdc=,iv:iixrw+C5Cluc1hAVtUIBuIcJz9RiIFihqTS3xLPA1H0=,tag:mVxnDp57gi6QJ96Lvr2Cjg==,type:str]
    admin-user: ENC[AES256_GCM,data:V+0/a08=,iv:yfT7CrUx/FSBus+MSvvwKZYTWjgXfi9UKBFlpiVHjoM=,tag:xFmiIsKOqWorqJku4SxovQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRXc1YkIyZ3Q0dEczM29T
            SUg1VmhXNVllOTExeWxmZEc2UkFyek4xcUdZCm1rZXNoamQxM09qdVhmSUdKWHMw
            ZytnMk5JVzNBN1BqVFpWSEpTdkhCSEkKLS0tIEwrYlZMZ1paNjZOem5UTE1WZnBo
            dTZMdm11djloRFlJMXVKVU1XeVU1aEEK+rO+1hBqBIExM77+NtutMQkzqPtTHZ6w
            MwHb0MbZhPUacMVuFlJvcBhea/vgsdeM5dpljEQG/DwgYIoRKxs85w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T20:31:06Z"
    mac: ENC[AES256_GCM,data:Wmaw9HYnvjpmZ8qeu7KTCQ22wUWxR+JViT63ZdUYjW9BIq8mplnAiGoEbpQbpGy4+uS0btHUjxjY1VipwvobBLjNSgN520IyyXp22urSdhKrM76RBRwEfBf82Azx/uu8ldB3COhvR97Ab2Xgzg8UDGTBiEhF0ctntzXBkwC8mDg=,iv:iKmB3Nn9tdPu6y2iZSE5VAVxFeZxiEVvaTOL4GZpbeM=,tag:1/7JhPRGYmhd80z+bQuBLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
