apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:1dMKdvY=,iv:t01EIaaaRIdHcW3yjYMyNcKKse31sj6z+/iK5ih4/fA=,tag:AonReSLjUulqO6i/CX+ogw==,type:str]
    admin-user: ENC[AES256_GCM,data:CCTy36s=,iv:n5Sc9K/JbhRmpFbtAYjldZlv3eb2MmeNRscmn6qJzSY=,tag:k0mvbio+4wBnUDtLkPw2Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTXlJaDJpUXFzNTB6cThT
            d3RrYUdlK0lJWGtWQjVvS3NTODNJZkZtcUhFCmFRR2ovTnVjcjFXNXQ1eFFWelJl
            SGc5WDBaMkQyQWFRM2NpeldFVHEyNk0KLS0tIFdOcjU2NldmMndnSkVNdTZRNmdM
            OFZKNFhsdVJKN2ltNWpRM1VncklnSEUKNHqYTKIJtQJSfMoG4AF9Zjhx1rep3dvx
            dxiabO6dkbUize5rOGzztAiFu8VCbSXos3qnFPWdVmBeGbFxUrFj+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T23:25:27Z"
    mac: ENC[AES256_GCM,data:zzPYt6/Ma7YkApo6m5T/mAf+YFnLYBHyDhLyTbJvGQkdyVwGSQGcE9dYhRzDl9nRIho1puLpc/VNdmHH7rS5hVOMxSqwzS3MM2FERYwPzmB6uvsbAEv58dnW0UGy1yHYU75/S+iSMt81wMGJWMkoKUTmHJxQSEJMbNRpbiN5pbM=,iv:bPE1dQJZOawjYZZsWlKWwqzO2ITiYI5UdmM/WWaZggI=,tag:w6vb1VRuVFeZG99qPdmJBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
