---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.5.1791
            env:
              COMPlus_EnableDiagnostics: 0
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__LOG_LEVEL: info
              SONARR__PORT: &port 8989
              SONARR__THEME: dark
              SONARR__POSTGRES_HOST: cnpg-postgres-rw.postgres.svc.cluster.local
              SONARR__POSTGRES_MAIN_DB: sonarr-main
              SONARR__POSTGRES_LOG_DB: sonarr-log
              SONARR__POSTGRES_PORT: 5432
              TZ: ${TIMEZONE}
            envFrom:
              - secret: sonarr-env
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 400M

        pod:
          securityContext:
            runAsUser: 0

    defaultPodOptions:
      securityContext:
        runAsUser: 0

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/dark.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: sonarr-main
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/tv
      pvc:
        enabled: true
        type: hostPath
        hostPath: /mnt/transcode
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: nfs
        size: 1Gi
