apiVersion: v1
kind: Secret
metadata:
    name: sonarr-env
    namespace: media
type: Opaque
data:
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:R5X6oAk8SVg5RXF/,iv:AUtEors4Kk5GyywTGu3LIPHfc/Qh84DZ2/zXElMV5nc=,tag:9BacgHZZZ6aXx2VyzNNh2w==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:4zojJyR/6z4kkLEC,iv:FXwmf/9S2i50xh+dccjFOttP57JK1SkAN4k5AS9PgzU=,tag:t8/cNyTBebkVEhCFkZr+1w==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:7D/2+hTI41u9Cu71TbQiYMZT3A//87Ai91BM8PrrvA7aiSCOEzgttvXk/YE=,iv:uI2ptIcixaXC5uS7m3kDm/TgrqeUtl8AMW8/NwQbwY0=,tag:B0JrIPj0znA7CGTPozIEyQ==,type:str]
    APIKEY: ENC[AES256_GCM,data:cHQKYV9OowSRYdvskjfYkJq+00gxLUDHtfkxDoCJh+1UZMjbjua8TqbiKNE=,iv:s6787QQzNkgWkJRPsxx/LAMBdds5u1/LADjTKaOrrQg=,tag:NV6VaoctgpQTb8Vpzmsqxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NS8zaGhhV1FlWlFJblBy
            MUp3S3dkVzJLTUlFOGhKZ2d4SE5iQ0RHZWxRCml4QkI4dU5haUtuNjhpS04yRXk0
            Q01Zc3RSaWxrTVNTOWp1ZUhLM1l2VFUKLS0tIHByaVhjYmFRbEVIVmhSWFhHKzlN
            Si8rdDcyakdRTkM1NG5rWVAzalZsK1UKMVcUQqMKs26F3jfFDIfNivJD21aOyYL2
            A34lE8Xr/e9wbj0GwIp/RCYz8j4Y2HcYr+JqevOvmNW7S01dk8MJqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T03:17:52Z"
    mac: ENC[AES256_GCM,data:OnH7S9JJ7gSxTHraTU7F3oTqVu6kvzMRjLN51huURmC0qherOiNrcczE418EjNTcCAQU5zPYdHYdgAkLf3vSnsDNJjyAYVaj+AbUQjxi8QXpCkFunwn9/mlliRCog5BqXwbg4LKHx9kIRYiDIN8lggv8ZnwMXCyO1GlmquRIICo=,iv:3pTRA1yJqdsVuLXAwwG7S0zKzkvYWD62J1McPKKytHE=,tag:jOmHYZkGa4KlYHxF/IEPYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
