apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:1cNZtz0M649RnipIvl959YwoxsndCFdAEnHWE8TqkYF2c/6S4EBfng==,iv:aJItMuuPQUl47cPbEHztMpaApTdn6e32lgYBAtKwzQY=,tag:BTFc4QEWeCnsraFKplhrEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM21BSzZENS9HN05iZXB6
            TmN3dDFaS1R2U0txeW43NzJJTS8zSTNnWnlFCmFTd0xQSnpESEliOG5qdktwbjRt
            dXNWWFdxQUFwUHVVSzVvdnJIYU9veTgKLS0tIHE0bDRmQWhCY0JUckM0eW5aN0d2
            WGJiMnBTMS9vRnlEajRySjcxWjF6OEkKKl1mLycXIbi6hj06HKVddeGRMb1yKNR9
            77fDzkyZhZMHB7KpY0xzd9CyYjy2UmlUj7+HZc98DZg1boeCd0UKlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T20:16:25Z"
    mac: ENC[AES256_GCM,data:Ng4ugM7czKhMhaF32XUGuK/9w1eNOmvKjDNADVXV58isKij3TqGsu3c/YNkW1GLTCWqX+GODBvK05YmeqBNQK/hg/Z5YmsgKITbcJG0YKYuxnELVbf3pH3Z9eWoQmCNM+1/zzRxq4iKgueLqWwOFspTFI3t8OmE2YhxDuBPoBg0=,iv:P3MOHRMn8h24fBR4w/xzheiM2akG2hJ9qZQKBaqrKnM=,tag:WkVdIoy10EMJhWAxMb8cYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
