apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ULS25AWsr0cN+ww6xdeKVdxYTRroWfW4gA8YE6h8+PBAHYpkwThrwQ==,iv:AGOkRFec6xLyQKrUTTY27H1uQH866rQzO0NQuexFfGs=,tag:Epu9bHY80vA9ubyWhJIdQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZGpCQXFRNWdab0c3L2Rm
            dndvZ0lQaURIMG9TSm5uYkY2cEZPbXEwSkhVCjNLSS8waEtvUkVzZVphRzVzUks2
            M0RjdGNPcnVBRkNEZFE3N2p5R1hKUU0KLS0tIE1BV2U1Q2wwMHk1QkpzVkN1K3Y3
            VTdzZ045Ukh3akdDbWRVVWZWYXkzUnMK3DQMRhR7uUpWn6UDuuix07ZwAQPrVG1h
            4ddbbvfj/VEcjdOkOa8a3xhiAmwzL5dMuD8AxnXozInfj9yA+d5mfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T14:56:56Z"
    mac: ENC[AES256_GCM,data:QtcdIO1FxWsjpx4EbY5GAgdg8ZvgfNEnwIREZ9VNqsApaut/Sp//+ha7C5vj60Co4fi9X9lrKUjjpWDLju+qCZerLAs9KaLIz+EE6dGcwxBG239MKTRJGsS9wZ6kMgwbpf/0h0fmw8OrcujRNbYaNvIzqnEnhdizjRNnPVHSVWM=,iv:I4r+CHnb7wDqpEValUzzpBl3d8214dfvhfE8Z6j22Tw=,tag:LTGsn9Coh+UPU1i1+CkkPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
