apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:nc3wWiHxnYOJxa1WpAOMsP8vWW3a0mlNh+cQhbglciOZEh0t++y/cw==,iv:SCBMvq4zDHPe3ugqkL00bBsopt+C2R4i//9Pl68DjuE=,tag:ZQWrsZ8yRoIUlNOcYdW3fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1csku9hc05cs2f4hp89w079czpdzpx89mj7zq23e9k9nscxxcfausx2yhzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0h4VnFLaVQ4d3NBcFlV
            MWhYQ2lSbFdndW1qRWEwckJ6ZmpmK3luelVRCk5WNS84NkdVMGNpdXM4c3BsRWJ2
            Q2lCalFRRllkTFNWZHN0YzI3VXFyRHMKLS0tIDhQVjNtWlN3cnk3VisrYW9HOEp4
            b3RmMFplb1pXV2swcjZha2toYTUxQncKvjOtH5cSauVVRJiM3Xi3dTsQ4M2Ejerw
            hWN0vhUVRDPVZH6/7qpgT1Lwznk6H4cWbkFroJIo72eNSadONVGD6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T00:44:02Z"
    mac: ENC[AES256_GCM,data:8OIYlh2xXur7wW9wtWLalAQ31WbGkcGYxjifR6T4zl3lUk8hNXWC5HAY+xdSS1TASwLDy0oY2KE5c+S2pgIGQuLYdQr7j4caU0mnQICLNeeqca+LY2jVilSscu3bfxtQqcbxblhhlM4HQZF3XHKt0fNMBZmDCzgNkp7xOPLzw1c=,iv:S2kZQKLm5Feh61Lx1wd8cSW/jmvNnPTKXmuZ/OAE9io=,tag:HkUanaC1heyKsEfLKbkJlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
