apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2b65qYTya/jd7LujCPXwbs3d+z5pzi9nQkOM0Q/td719XYzDeQypSw==,iv:BskFLr74kuuu6FBRUm1n4vuj1sO3MKU3u8ACuOQDQPw=,tag:JjwpfgO2v+4VI2te8bIsIA==,type:str]
sops:
    age:
        - recipient: age13tgynpy3lm785sydz78hxx5dlqp85g25an4tmekx5l99fdzzns0qd89t25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSkhuV1ovQWtYeGNoQStE
            VEN0dnhaZjZtdVVQTzU4S0FLZm5PYkxFMXdNCjM2RDJzYVk2RGlRNTVVcmZRQVhi
            VmR6ZnJuYjhHQThSa0pKY3h4Zk9lSEkKLS0tIFJSc0ZUNW1CSWNWT2RSQ1VycmEx
            Um9QYjhXOXFJRENQdC9sZ081d2ROTUUKYg5bQRtSIwszouSOwQhOPuyEPqXHFRRh
            Y3JnoCXg36x2f+6FEMct9fSOvRGwf83g5TF41l5u8AZIrtWfUb6ASg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T23:56:46Z"
    mac: ENC[AES256_GCM,data:Qr91MJ1fSYN7djt41GfVm3g7OQ0c4uUBTwSdO1RirRLZAmCPWgvgW4kU83tKR84FbRpkiIWolA9hwuZoBLUSbRld9bLqOEEB7jZYIIAEEQ934tvVD4dcYclmfxksF+Of0wUL4pTO7ULsdXSDCI236P4kK4O0Im2Q/Vi1DjgpAM8=,iv:n2X0xklBeRUXIxRTni0ajlyMdJqRJF75pMA1a6o7zyY=,tag:PqXFRKAVO+8vYpsb3hSREQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
