apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2Q40oGDS7LuLjQ60zT5IZlXEx7F5FXZm30fbKTHELDAnMlEGCz6o1w==,iv:bEHgArhltTKMw/FS971VUcnB118Ywv3z3oT31BT53xY=,tag:FJ+TLz/VFhc6PHr1dmuKzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Yk5vaUZjNWdQRFUvSGEz
            MzY2TkVMbzRSS3dVTTdTbTFQajRvNUVFQWpnCmJ2REc5YlJuNmpMWEl0ejJ6Sm1C
            Z005N3BJQ3lqUi92NmZMUTRmQjhHMHMKLS0tIHFRM3N3bXJ0NlNRVlV3dnhZcDFa
            Q1F5aW5PT29DRi80dnR4N0k1Y1ZsK2MKAdbhtE1lIuKLdMm13icWngw+GvA7v/P1
            rNyle3pxVcL3J6pLQGZsFXI0gGkZmMFrrvkh9zA/lZ33DQE4GGVWbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T15:47:55Z"
    mac: ENC[AES256_GCM,data:A/vIKPjDRuMa/J82KkS8EkbT+5xcEozV6YUK4Sr+fv7ZofqMafIoVlzGUrdYnwa3Bl+v8sTmJgckkU5YHSuxjnaLqNLw+XuO1VLJumnb/N/biSuX0LPnkWWqkxYc6RIEJt0Zvl02h1L2l3buEs6fG3U8TTzW46RpQOUI34OtRmk=,iv:4iyXuRMahQw9JvbmUYitSZsC8/wcoTBjHTQj3aMOE/0=,tag:ybwNH5RrnOnRfnICOglPPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
