apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Ub+UgVy09ItBlZWnz8Y7ntFWdi8Mns74YU5mw6l+sgpCXKdMJStSOg==,iv:AnL6Yc+4mogdnIRA9ytbpgjJWVw6hmnbFTVoY/85m2M=,tag:Ljgy9EzGRsRK87Uk/TJ3WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cXZHcmVYYlkzTEFkbUhC
            a1dBczdBdG1VY3ZUdTdyNUcveWhYRkVOV0NjCnQwbTF0SC9aTVc1VjhORlVUTmpR
            M00weHZ3Q3hjOGxIZ3lMemM2RXZmVnMKLS0tIDVlcnN5NE1uMWR2OTFHNnlUb0Fm
            N0FBbEpOWjB1Y1F4dVVuQkZQOUZaOVkKSNOfRbQcCWNgBtdXhIlYVWiPq18uLUtr
            +LADXkWdyrv58RFtJhJ+qDa0qaGdaaVB7l9s7uNTZOX7/Z+17yZ38A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T15:44:51Z"
    mac: ENC[AES256_GCM,data:aB4p+Mprh4V/JOQcj5aFq90fNXRWgl74gXvAFZmeaOGFlzBjsUkg6w55Qkf32PUWfd15Zi0rYYGTxnMTBbbAblKKPe4oR0uyZ/AENjYJfRjzMxkAKhblqxgSvYM7QQVv0Py584lHbrRaBEh0LLglM6C5hP/dpZpLG4w+bkrmEfA=,iv:ymHDtFxjPu+8jxD5WZrrTFf9IC6sRoqgqQoiOl/OSc8=,tag:ymw2ltbYB73xekt82/Gc9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
