apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.29.2.6364-6d72b0cf6
      pullPolicy: IfNotPresent
    readiness:
      enabled: false
    env:
      TZ: America/Chicago
      VERSION: latest
      PGID: "\x30"
      PUID: "\x30"
      PLEX_GID: "\x30"
      PLEX_UID: "\x30"
      PLEX_CLAIM: "claim-ZrVzhbS47TEsKRFmHbbq"
      CHANGE_CONFIG_DIR_OWNERSHIP: false
      ALLOWED_NETWORKS: 192.168.6.0/24,192.168.86.0/24
      NVIDIA_DRIVER_CAPABILITIES: all
    securityContext:
      runAsUser: 0
    persistence:
      config:
        enabled: true
        existingClaim: local-config
      data:
        enabled: true
        type: hostPath
        hostPath: /mnt
      transcode:
        enabled: true
        type: hostPath
        hostPath: /mnt/transcode
    nodeSelector:
      nvidia.com/gpu: "true"
    hostNetwork: tue
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 2
        memory: 3000Mi
