apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/plex
      tag: 1.29.2
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
      PLEX_CLAIM: "claim-uT78_rUxptJVJnQKuW_7"
      VERSION: latest
    securityContext:
      runAsUser: 568
    persistence:
      config:
        enabled: true
        existingClaim: local-config
      tv:
        enabled: true
        type: hostPath
        hostPath: /mnt/tv
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/movies
    nodeSelector:
      kubernetes.io/arch: amd64
    hostNetwork: true
