# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/clustersecretstore_v1.json
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: pik8s
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
          namespace: security
      integrationInfo:
        name: integration-info
        version: v1
