apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-env
    namespace: media
stringData:
    APIKEY: ENC[AES256_GCM,data:+7fx2xlIEVD0dlprdtUBwOE1q5w=,iv:szqieTlyK/KB+WlZPR7NDe0OPWm2/zSLi2o7eNM++O0=,tag:MqoYQmkj/OjPnd7DsCbqdA==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:q/LSN0Qu+u/8PtG/BNeyansD2uM=,iv:v7a4VFtsCn7XJk3rDKUgKH427xxAwd7qy0CnI7ctx9s=,tag:SS9s40aGSiEDB3azFdzSyA==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:iAozzaPVdTY=,iv:V9HJngT0HeklcNUmgISbbRLb6cuzEB97UXjzfC6pt/E=,tag:a1C/Qr8UXqZilck+5VW7IA==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:HynN7brfYNo=,iv:xfRdB917UDJkLUJe4uELPDq0w+PRrHBJa2+nYTI9SXc=,tag:NtvyqrJTf9oJip23uXQ72w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT1dtTFlXZFVQSEc3d0gy
            ajJ1REFydUdsOFlxS0VYL0NCa2s0UUI0U0dFCkMvQytLSUxVUEsxV1NmN0NHNWMw
            N21sTHpqazE4ZWQvL1MxV2t1OWF5cUEKLS0tIFY3b3pWSW1uZzVmUExlaG5FbUV6
            N0xqZnZEOVdwc1FtVmdyL21rbUdGb2MK+ISKn/z2WrgxoBmGAvnLTOcrtBPbi1BQ
            Z/yiysjQKVyY1fJSE8AkapxKkNiQzZyJgGn9vWa1s1D2rHZA2oEuYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:41:54Z"
    mac: ENC[AES256_GCM,data:RI74BoeiPJa2COHLs2ykxdzJDts3ZVtZ9qntsS+MfW4fiAR+ebyTIt3mZ+0UqJvUDNVziz0hwE/NntdIf+RkIj2+PxZ+GsKXF0wabaTmsD6kh92WpdaTz8dwdpLfI8CFSxfqgE2nRGiG4BbZYNPtxkSauZ2GiG0XuDZQVRE77J4=,iv:pmQcglAu88c8teQgQs8zLrXQa5NLQ2mi2pJtrKSF6EA=,tag:36Sydz4am+yx7BRQwr1vjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
