apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-env
    namespace: media
type: Opaque
data:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:EBAs3XopysiWE8Viwuxzhdm5HbbE/D+l47qmGRdVrqz3UizFKtBKnrYBvK4=,iv:dh4SRNwlgvS6EfJRCl+eH6XNUbBuhpDdjoc1nteFgnw=,tag:2XcBeZ8FyQDzgjvaEW2MaQ==,type:str]
    PROWLARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:It8DiGZ8zNrk7B1W,iv:VL/5xoQDJV+cADjUizp/YHYNHlch3BJkJObcNSY/FVM=,tag:UOA7YM+ivRhcZymVEJqknQ==,type:str]
    PROWLARR__POSTGRES_USER: ENC[AES256_GCM,data:Vf+W+VQdn3ekEl4S,iv:VANGLeaU3MmOC/YSD/g5C3gNqrjPt1raUiz5M/s+gt4=,tag:Ah9dk/91D5MWU5N4aa0p8g==,type:str]
    APIKEY: ENC[AES256_GCM,data:clU/tE+0HhUbtUJos/aiUR8L28C4H5Hm6ABawaQQWetupd2xe1cAptnM9KY=,iv:bbleHfv5JIKB0Lp93QIeopXPVxP4V+T0FL4tJ4Mgw3Y=,tag:IDVY8yntIDVGRc38XNs2Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZEdxQnBhWG1UZGZwMTBU
            bSt4a0JIY2svSG9QS3ZQYzRkSzhJWC9QNmw0Ckx6dWJCWWhSSEQ3TGpNOUFHWWt0
            cDQ4S3hFN1NxMTRPRmFLbWNYRkQ0dDAKLS0tIE1MMXVSb29aeERUdU1qTThxNGRo
            bUJlU09BRG8ydUQ2bHFqN1pwRThCbzgKMcYFjcGE+ZWj6hOxFlBxr4MK8yNfsdp7
            z5lmb8ET0oyj5pinGm6xuLYRi0pKBStrARbDJ7pMcWhAQUcg+BqGAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T03:05:56Z"
    mac: ENC[AES256_GCM,data:tmjMdTi/LL9THOShTbkuDlvr3dda+SNRSoiQ95rlOTHzclo4TJ9IVHxmD7IYvSPC+9QVCofA43ScFg6vsroMCf0QzddjAfVovAE4CEN+6h6Ukg1OS1GbAve6TiLQW01kaxU98R7AbaKaXqIlr0ipomDeX5X92JjBDnoSwTwWzNg=,iv:QA+zHDXz/BwykaJocIJoYWsRoIxu/g6UfqitVVdcMwY=,tag:r4nUHOUXyFAwYzefAHfkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
