# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
