---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr-nightly
              tag: 5.13.1.9362
            env:
              COMPlus_EnableDiagnostics: 0
              RADARR__SERVER_PORT: &port 7878
              RADARR__APP__INSTANCENAME: Sonarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__LEVEL: info
              RADARR__UPDATE__BRANCH: develop
              RADARR__POSTGRES__HOST: cnpg-postgres-rw.postgres.svc.cluster.local
              RADARR__POSTGRES__MAINDB: radarr-main
              RADARR__POSTGRES__LOGDB: radarr-log
              RADARR__POSTGRES__PORT: 5432
              TP_ADDON: radarr-darker
              TZ: ${TIMEZONE}
            envFrom:
              - secret: radarr-env-new
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 400M
              limits:
                memory: 1024M

          secondary:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.0.1
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:7878"
            envFrom:
              - secret: radarr-env
            args: ["radarr"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

        pod:
          securityContext:
            runAsUser: 0

    defaultPodOptions:
      securityContext:
        runAsUser: 0

    service:
      main:
        controller: main
        ports:
          http:
            port: *port
      secondary:
        nameOverride: metrics
        controller: main
        ports:
          metrics:
            port: *metricsPort

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/radarr-base.css">
            <link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/addons/radarr/radarr-darker/radarr-darker.css">
            </head>';
            sub_filter_once on;
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: radarr-main
                  port: *port
              - path: /metrics
                pathType: Prefix
                service:
                  name: radarr-metrics
                  port: *metricsPort
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/movies
      pvc:
        enabled: true
        type: hostPath
        hostPath: /mnt/transcode
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: nfs
        size: 1Gi

    serviceMonitor:
      secondary:
        enabled: true
        labels:
          app.kubernetes.io/name: radarr
          app.kubernetes.io/instance: radarr-metrics
        selector:
          matchLabels:
            app.kubernetes.io/instance: radarr
            app.kubernetes.io/name: radarr
            app.kubernetes.io/service: radarr-metrics
        endpoints:
          - port: metrics
            interval: 4m
            scrapeTimeout: 90s
            path: /metrics
