---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &chart csi-driver-nfs
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: *chart
      version: v4.7.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externalSnapshotter:
      enabled: false
