---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.nhudson.dev
  share: /pool-01
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions: ["hard", "noatime", "nfsvers=4.2", "nconnect=8", "nodiratime"]
