---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sonarr-config
provisioner: nfs.csi.k8s.io
parameters:
  server: "nas.${SECRET_DOMAIN}"
  share: /pool-01/pvc-config/sonarr
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - proto=tcp
  - hard
  - noatime
  - nodiratime
