---
apiVersion: v1
kind: Service
metadata:
  name: home-network-exporter
  labels:
    app.kubernetes.io/name: home-network-exporter
    app.kubernetes.io/part-of: monitoring
  annotations:
    tailscale.com/tailnet-fqdn: "${HOME_ASSISTANT_TAILNET_FQDN}"
spec:
  type: ExternalName
  # The Tailscale operator replaces this with its generated headless Service.
  externalName: placeholder
  ports:
    - name: https-metrics
      port: 9116
      protocol: TCP
