---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-podmonitor.yaml
  - ./grafana-dashboard-flux-control-plane.yaml
  - ./grafana-dashboard-control-plane.yaml
  - ./grafana-dashboard-database.yaml
  - ./grafana-dashboard-delivery.yaml
  - ./grafana-dashboard-network.yaml
  - ./grafana-dashboard-media.yaml
  - ./grafana-dashboard-platform.yaml
  - ./grafana-dashboard-storage.yaml
  - ./grafana-httproute.yaml
  - ./grafana-rbac.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./relay-configmap.yaml
  - ./relay-deployment.yaml
  - ./relay-networkpolicy.yaml
  - ./relay-poddisruptionbudget.yaml
  - ./relay-service.yaml
