---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana-dashboard-platform.yaml
  - ./grafana-httproute.yaml
  - ./grafana-rbac.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./relay-configmap.yaml
  - ./relay-deployment.yaml
  - ./relay-networkpolicy.yaml
  - ./relay-poddisruptionbudget.yaml
  - ./relay-service.yaml
