apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:gFCO4QJuFtVRf/OriUIbiiOK7t4Z5tgbtu19s+Jgix0lx6TTwj6KPntj4ACcFF7eaIQleg4JwDgYg+7MAZvWGfDMVm7fslV/xtEd8ym2T86E6iYCaS5BKXRaoP4ajA==,iv:OCtdHH9CkzXWcdv7IqFcbBFd8d4CDRtiVR3xbIQNQYU=,tag:Om7vvkAWny0/9z4eRPyDcg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mqvW4UTQ8LcjX4s=,iv:OJM3r2s2a375uz+nbThuK8BRuw8krCpa+lGUjq+JWos=,tag:8pOgm+SfROR4MDzAMUB1og==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:G5LSW2zItGKthlo62HR7004MIDnHUVl7V3Zg,iv:94DIaTKLMb0LqMzMksFZGoSNTI0cPd4BbLP0/l956ao=,tag:d3CrlyueUe3P0DafAdZgoA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:8W8lf2zjyQyj0QdcsyOsM5ZgJr06qz/vCe5QU80oiXL6SB6D,iv:X1Olb3E74pFJQ+r4ZrpP7IQscFR+yRgDQZj+9iUjPR4=,tag:V+7UFnikskptDHFYGOXPrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWVNnSHNheUZmWWhGK3d1
            NytKenA3dXZnUnBjUEduUGlYNzhHSnYzUHhVCmM1MGt2VllTVzBia3RQWkhsSzJt
            cWFsekpCUWdvaGRCZGhXR0kydG5lSG8KLS0tIE5ETUhRVWUybkp5RkFyMVZnQnF6
            OXFOVG9Lb3QvanZNc2l1cWpiNFNRMHcKBql6fhdyWD3wTUhtnzal/81oZyzy44Tw
            c8r1moF1fNcm0+0S4K0COdy5c19nPy3y4KQViS7yc7fsUZma8Kx1OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T15:47:55Z"
    mac: ENC[AES256_GCM,data:AdyGmHHUNNxXAyARu5UHVsfsStR3IkO6ozQ6LTB1lkyYWr3x5mIHj+7ZAfq5MRHHdYNaQ3gDFTapzNHB5qmdX8x8jqj6mD83BSOWWNf6tc0EMon+sX3s7nwTKlPrp3lLEosdXlQJRbN6217v75qpYKr6V+Q6PpX5ki9NWT9Io/o=,iv:+NvN0iYtOk9rFjU5SzVBHTcbuT+2XTIKWc9pc7Lm1+4=,tag:Qk3uhS64Ml7Qt/tlZ4PKPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
