apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LCf5GmlVPyKzB2o=,iv:ckHh3Wo95U+X4JA7TRxL+5R3nlXo2Qm20ZnSpJrdjuA=,tag:l0lVj6lvVuPjFpuDleLaFA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QH7TKX2q+SooNWjgqVvGK3HI2qzmoy8So4u4,iv:TrhquTQDPpKOe8QKef1GYrq3nIm8dJ4uJck2d0PW4dk=,tag:eebLdFfDctsvJIwzSFbh3Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yxXkRCUPtaUYoI6HeLHvgyAz7MRMyhP+qbKOGIUd0gDAYIxU,iv:bBLQ1C0l/0mbRdVMvA5Dg/lVWX6WNwfrSEFqkd4AetA=,tag:rXqyEDWPzO9fZ/OHjJrURg==,type:str]
    SECRET_K8S_SLACK_API_URL: ENC[AES256_GCM,data:7xCHQjSZQujgWE5HIr8uwBFxYzIwF884a3GV2mhEcGuPJVBctYuvXsyF/ToGUqPHwDtf12Nm5CTVaVynTrHTqPqLaauohnXMT6fl8Ha0rw==,iv:/gIBVS9889nl0Ns1Dv6bHyKngm9FW3FsG/31v1edqRk=,tag:wV2jUxHGjOtXRgvDhRg0ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVXJxNlY0RDFYb1o2aEsz
            SzBtTHFBdzYwb0tkNXIxMHNaUExTU0N1YnpvCjBzaVVtY3JFZEFLVXdUUjN6eGt2
            eFMyYStKdFpBQktsTUFmU2ppblkxUDAKLS0tIGVmam5Sd2lQMDMxQzRGS2NkK3d4
            aDIzcnpSY0x2QXRocTcvb1pVb2MzSXMK2BwC0M8uvdhvdIypudtbv5y9WDvm8KUE
            XPeqP4ByHnS7TZ+JDE6Y6ujPivzM3mMWqGRwx0+iPaSfqwvu8WCBpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T15:53:28Z"
    mac: ENC[AES256_GCM,data:SkjxdAaygrNqjBmKJQjbCh+n3tmomyd/tTX8kpiX5OjEsNIjFDT+/b2aM3s3mbWCxe6FYk/aXOmDlhPmmbpho5WRLnu7K8qv4oq3KDY5TCiWgQha+1vt24Nea2c4PcnwhtkI3+TIzMOknqRVn5I3wRMmj3eDdQst8t3ZxrS0fb8=,iv:TYo1kVm+euSzQi+m82+b2SaKLBuHdZ8Bn3fLUN+ahPs=,tag:YZdxAhy1pkuvL8EyEiXJiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
