apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:I7fNE75/khSRSTjA0EjXvOiYbfjmO8L7j262jp6ehXAye3GHMi0oNqRTOH0nDEJp1dllx1Oz9wU28golkWoeBDh9XBRTX8Ml3+uYWCqZ6iB4ONVCL+jJWdYqv2ysEg==,iv:Qqsu66FDUw9KhNAQqcIsyTvvyceX2PNARhlo5b9yg18=,tag:PUCv17fPCC+f7eu0gvHiJg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4FS3NxJ0a0LcWwc=,iv:NaJqFDBH+1rWeXj/bdUK+MRXVqZ5ju6UcLrBQj92seo=,tag:8CwFwr7UUamhlqM6A4DQ5g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:O7iEzcvL4Js7O+0LJA4cJxqMM/3oOUUI8FK3,iv:Yvo5XQhe+Z3lYvKFkka1e1ZULJ2ooMDt+jrTV5CdiNE=,tag:s6QgbB/HtJRsiINOXXr6Lg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/FO6HnECBrIqlwMa5WDDee9F4b73vpJNLDfxJ6vDEBlnyhs/,iv:bqE8FSLTH5TVUXrsnbvVYxAGOmg6k8rjtr2w0cLzk4o=,tag:2YRS3ai0CMLndwSm4UfmUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWTlsaEJFYzhVc1pLK1Br
            bGtKWDNVWDdubWdzTDhyYm9SMklEMTlaUEFvCitUQjRYVHBPSVd6cnFOblZFTit3
            VTh1QU1QcnFINVVPK3YxeHArKy9BZ3MKLS0tIGE1enJXMFRoS29URkxjYUN1L2tX
            a0ZzZ0ppbXFncnAyVGl0YUlSUHVWY3MKQeBQYsXvLy6B/25dt+rBy3HeaSQyrC40
            afLukUzEpN70hsevtU60N5S6Vj3y1KaBmU6ccoWySjjsMRFQpBoTMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T16:01:10Z"
    mac: ENC[AES256_GCM,data:lJWuKsaaiY9/o8GyPAPj8KEA+0OtU8He/s05OXpX9khsSpc6tu9T3im1Hk1HgDE7eK6dM+KJ7jK6YFhh/KIb9LpI0yXdbc90AnzsjjXpYNeQnj9Wwz1rxq7jzg1wzgZdeHQaD+iZh4P6ozTjG6SXf5cfB9CDppxvsPxQhzdlQq4=,iv:GOla6/yq+N7W8BJd2iniFxfHwKPPEGGZntSK6AiwUGM=,tag:OrJJ7rXMYD3wprfL3pbprg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
