apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1hH+Ss/TX2uIKes=,iv:o/juM3bJi6kG6apAYJcp5kMC1LUCAcejOAuw+P8NRWE=,tag:60cTW9N3RS3CTC+gEY52nw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:otUZv//hNz8JgLrx8RxZdLJNhaDenTvtFQaw,iv:W3MsBY9RDxFtqUjjeiD0tYvYmtDC2qYfmD/X7v0GtoU=,tag:iZo3yKPRMOeaxfAZd6m7OA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RIpSb3BEdTFFDe+wwkAmYCudgVUt/Us3FSFoUvceFATJEk6A,iv:90cm6MnOyFSRDHV4QCRt+MtTlaH35Gp/MB08I8WDpaA=,tag:o2cuwoTnyT+3rdIaBgDAwA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:1hZ10xfdWCezwvvwTQ0Ctfzyw/Xkv9M4SmztXrzd4OU=,iv:OQB4CPKh9r8bkNTkAGbLfnonREGGzUBgIizsH6RPqG8=,tag:6gvEErUAW9MWwPhqIveUZg==,type:str]
sops:
    age:
        - recipient: age13tgynpy3lm785sydz78hxx5dlqp85g25an4tmekx5l99fdzzns0qd89t25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdC9KRDlsdm14aXZyb2xH
            azdveVFJaGJtMEFMdUtWWVo2YlRYdGg0MWdRCi9jaFpyc24xcHY5ajc5VjBUOG9J
            eXNZV3lhd3ZMclVISkRVWGE2dUY2YUkKLS0tIENkNEtMelpESlpSbW5sSjFUOG1P
            OFpPQ1RPTGpHUG5DU3k4MFJONFB1bkkKYLeUBm5OJSqWfTLxg9Ld17lDiWwovvfN
            fgWkPSgXUUBrNA04HTPap0nC8CoGtTa9NWSVThh6OvrUtWEScTu1DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T01:31:15Z"
    mac: ENC[AES256_GCM,data:WbjvL0FfXm1maiqhDZ/iZpNk7nTYvWwmyde+7t17cLcAyZrNZSP0N9Hx83ESehJeLepAPyBeiX3XYTY/IrUJqsbTSz6/4ZqRBNn3hT/OxWqe6WC9qnL4kvwu+QPtIlh2WVv7hY2W0s7sQaYDLUM4+vl0941u5nJj5DMCeA0WzJQ=,iv:k6Iev7GK+QfE4b9GDyi37dLNC4ndleZ+bfC1nDzAs4s=,tag:89I7h58m3Y95fbCuyzWTxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
