apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgAry+/eqiK+bRPq+O2efSR0YEo/FoSUjHKwDSlC1UKnZ1WF7dF0MPFeXeIMa/fsYux9G129A5M4RWRgNh6qONtebuxwIJt9oK0sotNAD/MMdAgzaEV5Gqp5x8qBOAOoCb3zT8TzyuRfZd3gyneQnP/O7VLlPkFhLxLLhkBiSC1dwuS6Bl0aAz6A3kNZsCFnWhefWKee3Rrnj7269XaNXB46LVxjeBYiYVmJdABPnIvzVWlswOajJtFxclvMcRJsnveVgSkt4Gfol7M6e5DSDlJpIQCmAS46S0bQl5DsgYNK81Wanu5K8UMGRzV7kTOtdv3QC3815fgo4uZAQePPoC8jAGs0HJhEnIcCwZnD02SbvzWE8MaeYDzwx00Dv1KpoVktVnkr3A8E2Sb+bIpcLHamfKnbRZiI1njiHz+ch9ign1GYWk2jHJNVq81hJOPkaXP0zJjZHQCSZDPaeVS7g8j3L/qNL37EQXDd+XIguDu3RY8A7tc3CUeYwIi6gIRrnwoe6xhLt9J3UBm+C5//JAkkKXXq/ZAeD6HY9NOXbCIAE0lP6YS/ljf4cEHGPAVmkOrDoNNCysgTmeOs2CuXUQsqgDT7YqqQ14y1Wslw0pYf7SdVk/07kNY9C2I3RAJ+7efvRxbSpy+yH5nS/80P1leDe7GOrsS3hdbWz3Yy9bqp/iEgHBtCYI5ZNgVDxyzbhMmyomzUfwl9qk3crf7Qd05wpwwbkxWV+K22qV0L/yyT/+8BUlIuqrZU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key-secret
      namespace: cert-manager
    type: Opaque
