apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgArwIbTTBrAk3KP9XRh+pmMjIC+tiXFhN04FOFfXQStrITTYVl+KoqFisd7UfNUZHU5SOQ0dtTswxzDUDRp3ste8Lu8ITjDO1d7wxsXS73nWW01bdsEXyizyfr+YwVLGBhPB8Uyh5YfYJtqjXSffdiZB0umpakHNkwtbXk5Vtk5EqEeVZjRU69XUAwZ9X51Kwpsz7O7mK9g7rUkwR5kz+Wo8GhT7vH0x2nRowKKRNBFcqF1Kn7yNlQDMgXL1g+rB14uw2jqdjB0t5m+eDj9gBG8/xyO6kV2Ib6BNUlD9p3RAWrFOhulf90HUypJ5ZIbgYcC6yRSpa5qlt0CMaYQcuBDbPfzTUdlzwQbW1kwmptxZ2bq+SIhidyZbplI6o/KGIkzhgNFRWFPEnIxAA08c7V5GJ2RlGTlU3jzjuiRFRce5nJWyZO729k1XTdLB9lNUtaCFGS4uq2DZzJarRwGbTfPUSHB39hzKY16HJCJB9H65M6VxKtvf5FvZluvWBw8TR2lGyJBbN9tQyF+7VhvAByQJOAaMC0zxsaRGjWXvmPyrABk3oAnsJ4V/xFRyUdYWLPUFt0mOvyRG9ZfjwpSTmOxw8FRDJedrR6EYHdhgijgXstuO8/y7eFnRz2zLjfk7D4OcdufiyoHGO6rceE0fxSJSXBvJniiUyCRn2eLxDAWnSL6WOqewaR3FUgSrRho5ViqCJMyy4IUXDMPWaXosbvQHF5XExAjTN2p+YUm9IAdfQbIzcoPrSWb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key-secret
      namespace: cert-manager
    type: Opaque
