apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCiuLcUZ6m2uRmhTTAZ36FzJZDTYe1ei/qcEso6bbD3k3LKKrLQD9saU5ErP5R2jh8lvH3MAx+Wz3g9d88Mgyo9EA1Jy+UMnUfwfS694H4ft/TT7rPsqrJ82U75e9WSUVdwB1hBjrRQRg4/lwJj2ZJXpt72o+o+h/N4MPF7A9rhVFoIyLZ7EqCeL1p2zmzTI2EOYkbzyx9Ir72npjDt4A4pj87LDG+/X+vJy2phxV0CGhVzSr2le0A08BnVl6e4Xu+rsiqgl2ADomlqkRhCyGAaiPD2ZHcgIiT9cEKIrj9Xt1rlj3k5GZhjjzo2ctR0DP5lxFQMfN3VMUbc6birIUTxf8ocqLdH8CxabcE4x3YG/nlyTUBuE35exdYzUmS9l5fzN1j296eOztV19eFH+Gt8Ae0J2Ekha1CKOv1YcGVdOBrMtGB0qZmkC7+hgaJ6wU0B3nJxFHtZrZ/nbFIwUMd+o2/G1LrVbnbvsPDMvnuV4ntXX/yU+bQ/sGQs32IduwHHMrz2z2Kq146k6GsxFselSce9+IddIUivMHzNcLRIDZ+OVgMIHV3OAmngZPimNq/F8l8XMLBNabyD2iXo/WG+ruklzR0GieiChxgSXJs4rxvqZ8PicjyRFlNnNo4NEQu0agCVV+a/naIKEhnH1NTdbuJrxkvvIzktfo9N4ieSjBU3yAqSIX0SZS7XmUEjXAkz6GYc3druom2JviHqWHqbEHDxsv7xQOBt3IwG0WtHOlfqDsqncEY9vw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key-secret
      namespace: cert-manager
    type: Opaque
