---
- hosts: k3s_cluster
  name: Prep k3s cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  name: Install k3s master node
  become: true
  roles:
    - role: k3s/master

- hosts: node
  name: Install k3s worker nodes
  become: true
  roles:
    - role: k3s/node
