apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nUiYz6Mc710=,iv:DkfBU0t7wru4jjoE4efj22DinhtCjOR4gxoHNE/jJFg=,tag:2/2bdUxF373J/iXQuZIffg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwblVLUVg1TWdrZ3R2SU1B
            WEtzdXYrQ0JxN1B1SEZkazlHSTdVVnRIa2s4CkpiUDdzQXFOM3JyMDRLbisxZHk4
            NEUvVjRnbXVqRVR6b3RLeStjQmptZVEKLS0tIGphb3hYVXR3Kzl2M2tQclhpMnQ4
            S1FiRGREVGJpYmpIU0o4Rm1kNXRwbnMKa2FnX6Qed8Lg876L7r18YPiRfD941E5c
            vbrHP14eKYqj9cI4ehBrqofkmdTS2Z2ir2UlRX/NY2ewJizv3fms8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T23:55:04Z"
    mac: ENC[AES256_GCM,data:d7NHEVeEieFWivh3t3FpBa6nu7vQRw5Qqze0Ys7C6t+SfWPd1z2hlqx2QnY5/d3/i9ic++GK/QfCSBr+1C12BjYjRIS7r6wTqhvx5NtguNn8ORfmFNdmzWAR3PLGM00bgLOVovyhK7jslpnbhvNm7AK/Ns5UHgDnJiUDSBpY85k=,iv:4P1Q1bWcRNYhztN0LDa7wkWRVm9odrydHNWonwC2Rpo=,tag:GJdhp0kN2mpCIrAEx05TUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
