apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bp46gncp18+h2IYs,iv:VMhHMud/u3gG9/UqpchoebaFzO2aM7yqPucNxh8uguk=,tag:WSmW4ehjGTMWXMnqAcGEpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVWZJS0dzUzROdWtzdmU0
            emo0UEJ4azJiTzdZL1prM1daY25YWVBuMWtvCmdGMVVUbG90UXBJQW1MYlI5V05w
            c0xIZi96OENYaXRQSVJWYkpsekJVVDAKLS0tIHdPOVpXTUM0SlpJaENYelBvd05Y
            WEJEOVZLbVRtUTVIcmNScW1USHBxNXcK4CJsgDP63OnpQ2S5tzHWIHuVfQuFTdKG
            g0YiSgazJeoxtg5/KZTl7hfmdNk8xxPKk3XvRtT93pfEObOkQof1cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T23:59:11Z"
    mac: ENC[AES256_GCM,data:xcSgTSYjODwiV/49aDq6DA+BAdxWSQNAvn30v3OvLUzUYBHLxJVsKgdjwrJp65Jk2CRt51ffS7hAOUmyXuZumb4H9NSRzFsFT6VIYJbZHsr1d2Sp5HX35Q3/fF2++Kf9b+QLk1E5UXcM28+iMbLlGemW/FQ1JGeNhgNqP6iNSlU=,iv:mXPR6pkRJQWkVSSCHZqApzropmbbvMgXz59tXns37qk=,tag:y730OOPMcb4XP8zvWQqNKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
