---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-operator-oauth
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: tailscale-operator-oauth
        property: client_secret