---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: tailscale-operator-oauth