---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-config
provisioner: nfs.csi.k8s.io
parameters:
  server: "nas.${SECRET_DOMAIN}"
  share: /pool-01/pvc-config
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - proto=tcp
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media
provisioner: nfs.csi.k8s.io
parameters:
  server: "nas.${SECRET_DOMAIN}"
  share: /pool-01/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - proto=tcp
  - hard
  - noatime
  - nodiratime
