---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: media-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-volume
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
