apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:o9NUzvsu0ehPE4vD1zckB/1otRVLHSkg,iv:by+dg/gWNPZrrT3VTtUPr5U029H4RrLBsQVjpW8c8zs=,tag:rzfJ+w+OZ7bPSu+vVrmG2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV0VJcWZqc09HUmRRNG1t
            N04yN3hSTDMrTEFzTnBpVHJoeHQ0MDhQODNZClJ1RVlEQ3pSc1JDUnZXbS9hb0dV
            YkVNaGx2aCtYOEFLd3l6YmZjR2RMWUEKLS0tIEtXSWsrNWE4REFLRjg4d0NBaWpk
            NWxTSWtvRXlwbDArRWFsQi9OTTJzZFEKMuHZw7tM1D8O5JjG3Cy6N9KNm9sMzh2j
            gh+XQkAnxvGuXHqEKom7ZTQd4MHAohZ8mY/R7+3GALcsVquY5Gmrvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T16:17:54Z"
    mac: ENC[AES256_GCM,data:EHWoQMCn/RQge3Kh8bXsJDcz7gakafJFVKKzaak+cueWQ6iAOb0ZZZqg9NgYgRBLocTbSBnVFw22+hWRc33wrdJftnt0nFyh4pl/LS7aw+l93MmZbNoOIdY2n2GeM7uRo3uamcmcyoZVf5qKPcObedDFV+V+aBoG011MWqjjEko=,iv:axPQwC58tumtTaocPmUOCge8QDz1rYPQnxm0Ta/72Zk=,tag:6OAbBEtcXXVLFGKBQZLejg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
