apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Pq+9NITDbuM8nSXT4jbG5fx0XN+m9v0j,iv:REATITNCL0u6betALtTAvhCuTfANy+bONC38llqDoME=,tag:OftoO6tKJCBZBlf7U0lUuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2U2SmxZYnFnSm9PelZV
            QjNlVnVVeVNzUzhCRWNOU1ZPTU82UTNRQkNRCk1YSUdWeG5HdTBCaGwwMmRxMUMx
            ZU5kdG9yM1pNVVkzRGMvWTdnVkx2WkEKLS0tIDZZZDNkOEwvVkZjbUtWeVEzV1JI
            bW5LMWZ1blN6K2VxM1JSdndSWWJYdzAK4ozw7WcrcjMsvzJlwj4giG7rRDqNaa/R
            QI28/em7oBAWTM8szDyDiWinlvMr+EzPknC54kHfcwBdFHrHTknCjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T16:01:10Z"
    mac: ENC[AES256_GCM,data:Ayb9czwQ/nxo1yyKs9noSe/r418cjidu3J8b9BLUKE/3Rw3e3W9aJUjXwU7wMrdI0uOy7IHddEeA50sh1elCfUOl65rvfnNHiba/Z3vglaWm9lH5fx8nulo3kmA4vjMAkaGW7yI7yEf0uQK3//zla/+lTXDEhx7qLJzjiNAe6ms=,iv:kijNyjpupkHBw0fnzfpIQlaulYgxeknMU21y2mrjF3s=,tag:06+xk4260WXBt3vuRdlHYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
