apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XgWJXkVhrvnH4L/VikPCBZrrpIm+1PfJ,iv:GMKlvXMD0ziCydQVaVhuUbx/L0d22OotWMIPIEQ5GQw=,tag:UcPO8kVX6IxUMqDIVnBiMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYnRwc2FOSWVNR0lGMUFz
            REFwdFlFY3ZzcHpzSnJLOHVYQXF6QnpXUTFjCjhuRDBXY1V2b2EzVUFSRFBMdFFh
            eER2QlZUc1NOTHdWc1g1MTU1ekdSU3cKLS0tIGpHUXlxRWJyZ21pMnpyTUZrWGth
            TXNrQk9kcjAwSDN1MnZHdlR2ZlphSWcKE8PX9zhD2dhecVAZOXMQUwL1v9Eu3zNM
            6510rWYqPvmzfedKVBcj3EUeOOU9FiBNKyPdM4y+hTk9ii2kZFpf2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T15:43:27Z"
    mac: ENC[AES256_GCM,data:zQfn0EQ6AX2TE+AVtuIS3LGip10yFsC5lOySznuCzSxmRGdfyYYZvXJ+qtnER23SzSCl1qXbEnawiATD+j67xYAsGw9LcNDBVZ8okzOFCnHlEKl9HtsHEYKYGdBnTK9Ufg9e0hIO8GA523RTOUxXCdI129huJSQTlh6iRxhcRM0=,iv:EtPzgE/3I8xpaS2chUvR2okHsjwTFuAwK+hWd09tyXo=,tag:jM+US6OqcbE80uF4iRHQcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
