apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:llH+PmT001zI7fSxl6Bp+UlcGGBtEwpj,iv:uWwFG5tLmgbP10P2G7Jtyxs03DY6qNd5VpZtTVH6ppQ=,tag:oWUxdlWUhVwMKHhAdX7qGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZTNZajhJOGQyaktla0FW
            M29pQ2tKblhSR1JhS09qbjl5cmQxS25QeGdzCnBkVzJoUkNtRjNNNmw0VFFxbTNH
            cnJtUzRUdlNrSnA1NVUzSmZvajZRSjgKLS0tIE1tcWZMNXVIRW9aa0tCT2xVZjlL
            OHk3WXFMaW9seTA4MkExV3JRUTBraXcKF7veeqlm07mDRy1WTAPJVH2q7sO6eHnf
            rI452MmXV1IK8KvJRvQ+S9FDxC2AyxngJ7OI9JupuitCYD7iRaBGEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:41:54Z"
    mac: ENC[AES256_GCM,data:SpF8jE+tqopP51XG6xsKvb81hppqLW03+nwRLnDsYjPXuMTiSJNT0z5WF1PGBfVi8kRQaVV068mHF8YpjJSaPu+Lsqd+Y0MSkSsuNvAyQDTP1uLB5TC9WeNsONw7N9hszZdm5jN4PiuLBhnvQLAVhdKPqLPM4UFyYbAUKj8tEDE=,iv:Q5ARCKErjXJf8ORzpWyDmULYrLavMoNzLzS+M2V+gJA=,tag:6rBml2UdpVs3wt94sP4d3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
