# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:52qz63XjPbUCUICVIt2829MqjXEJIDDb7e4n5nDfx1qVTUAxvp9Aag==,iv:uWn/1XBDqvq4k3RoynH09IOruk4wveEtVWrjLiXJrDs=,tag:Tt+jh9tw6Y/9zRi97+ytpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN1Z4VWJCNlN4YmV6SnVN
            N2lvZk9wUWkrc0NFRkVuQTcwODVlTkFvZWtzCk81bWhBakIxQThYR3l3UjcrVnRU
            dys0WXI2a3RwbnE3Tll3Vkg3TFV6TjQKLS0tIEN0VUFrUTUwNWJIb0ZOT2s1QnVW
            MmZnS3o5UHV1U05Cd2VJVGhMMzhRQmMKt+atFi+H6ZAUyKfVRStfliXiT3Sj2pP6
            kUrKVHC7VwDHj5V6+wM2za0kig0foSJjtN0mE1r9AKVTpShHD1lEnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T16:31:48Z"
    mac: ENC[AES256_GCM,data:MSbphL53fNuh9OeaVk2reMVXmvyBJh0nyQ8iSlsxvidXLZDj9HblaNwpd7jR1Z43KJkoQE6E+MxvGWchtJ7cbPyUkuz6/BwgyNopNbg2c8vv2C8LHrFMF/svaDe7juI8zxkCtIqbBcA/TOFmrucr/0jlCWqTuRaO+21cgypU+1k=,iv:QGT0jd3f5ihAgu2sgUWU772u+Fu6tiQerkJP/tBd8cc=,tag:8yugHWSvzl/BsGJbP+6XvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
