# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8pc+u4i644yXZ0BQI7uZYQk2bG+A1yX0krr2AObbYgJgs9NalhJ1nA==,iv:pcrQ/VLGzawMCUCw3Kw80FXxb6umI+gaDbUvRbrFONA=,tag:dU6kNu1x552jIq9oiIEMpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMjkyeFRjZVU1RFRrczFX
            ZzdxQktiR0NrQ0NBMWRoNjRKa3d5L21TZzNzCnFkUjJ3TTRaUkZkLzhaWWpIWDV3
            eVV6eTlrNklvQ2hoeEJQb2d3cVJsSzgKLS0tIGo4SDdwQnQxSm1KSUdEQ2ZBd3JP
            bkgxMngxZFZZV2tNNmVRQ3djZDlSS00KRl48gtfiG+KwEcE0A3IcOe7BViWO/XPM
            tM3tbIEke5XsaJoVyK++YdYOfZrhkJD4Mmq7uSKqAx/o33/yzCEWyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T06:47:38Z"
    mac: ENC[AES256_GCM,data:xbRuLx4IvRKuWECl4R+G0Tt4Z0y5Xk7aJ49O30cXyrOHputC7BaqFx+lMfJ5mvdTmgO3S2CGKFkDWkKA+xHHKXw7XDMWziOsE0HRSHG+X4hO7eOtMA/nZIgXKSpa4nCciPGGwCbKlmpmhI2CnG5ecyS+TKGVLY+fODRrQuyCRuY=,iv:MFUY0XluAx7QYVGt1D+BaNOFdPsYnhU6j9VpCKbtPuU=,tag:6ln4DbgAQOlKgKyoqhVJSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
