apiVersion: v1
data:
    tunnel-config.json: ENC[AES256_GCM,data:ZrQzABifGvGYWE7wP5BCVGBzSYen2Tzv7DD5xdlIx1n28FzhHZv48IB9GAa30dEi4Cyu7s6NjVkfxydRLzajcFlrMGsg3ZD866HWtwY+pT7L3ziuio5Q/vklOoTPxJ40RBmQ4u11bv9+P0KdH4LLTLZBcQsfIRi2ClFodUG4Aya+WQJ0jwORMIrrXP6AEkC0S/7pu6GOS8fTdURZnjn0EForSRouAfF29XbH3G+ubVPxDCmi0Ks5Hw==,iv:bs1KTaB3vX4d6gQuVmI9nqbjmxBohfGHrHrgddl+/Gg=,tag:mcC1dxrfIJGYh1kIKBJ7UQ==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: cloudflared
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUHhUZDBlZ0RuWExtSXdv
            NlA3YXpZWlNpOUwvR2R3K3Nwd3VvM3lrVEZ3ClRNZDhPUWltalEwWC9LTGdNTWNX
            WVJ4ZnUvSHZ4K2o4eXhnVXl6UGJVTUkKLS0tIGd5cTdTbWZMNTVHeEdncDRSUkpX
            NmJKSUxVa1RTOUpERWtSUDQ5R0NTMjQKjpL7jrAT86c/LxEFZG4axDeg3JVkjCVT
            Hzf2z9Hw65y5QIEv6bg7I2JJMYKe5Hs4w/PmAkHFuJlsq8KtU3ekkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T18:00:57Z"
    mac: ENC[AES256_GCM,data:kQZCpk/kY0NiYzmcWOi1w3S5MxeCBVKf07sxyC83QhO3gJJRbN4gqxKeuiwFB3ev/RC2ACtzyGW/J+qYJPOSRhBWYtbu0cfQAO8JCKFlMrJK954/fqe5cfJINOdouMvjodzp8hHGkt++OjsM5h4qrDunksWJjvWFc7dsn4qFaKU=,iv:RZ86iaPRApjaL2rfFHcAukRk9FKW+4iP59DUi58/vV8=,tag:oCvmSQdjXkETar6f8CAkRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
