apiVersion: v1
data:
    tunnel-config.json: ENC[AES256_GCM,data:FdW7MzlfEKajf6jDXp1W7Rnei9M1JtLfRGh4/X2rnZwgFexKe4ee0E7nKyOPdMZ62BMEsmH0uEh2FAxPAVpn6oDzu2Nl1TYb2WOwpuu7Xh3H4I8C2mXwfVQtCW1wAHj+ufH0OA6c0PriYPjuwEnu1v03cxg0ZwWUGZtwKKqklw4sciAV5Zz+7SjoJl7uVyj9bbHEEJOgbNxFkerj9tddBLdrzLg0HeF50ZGNUFDrQLXb8yQH8oEJAI0gM8IFBtWpWc7ACR7+kTI0jqbpqMUQgyhSu3B7y1CT,iv:ERBq/5xwRASTY+ANb/3iaF/K/d/Qd4M2jFzZlh9yajQ=,tag:p0PYmpBidvXFu+Kpkwy+TA==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: cloudflared
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTFMwdEZxSnlOWFFFZmhr
            aDhvYlFLdWdjcmtTNFcvVWE1Um1FOWdqUTBzCmxKaHFiUFI1UE94N1ZTN3lGME4v
            NE5XbkhqaEgyMWZ1MmZZRGUwc2FYWEEKLS0tIDI1NnMzQjRqanVIVDRreEN2V1dv
            aVgzWEhPaHBmUCtFMkhQYjQ0anNGeTgKbkLlpIxveteRYL9ws0JuzrbLhCOvHMAm
            X+URmQOuBzo8pIDJa0cz6MZ2MTeCLYdQhr6ziqjKmmOE8KbmTz1Xlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T17:42:28Z"
    mac: ENC[AES256_GCM,data:n7VtZxZiW0WKbjWswnCwt6yJXgJfNBLbC7DGNwpDBC/0i7jUs0oY6+26PR0dwlqTTxXuyocXhVrtgXN25/4pKuxk/KNV7IJrjGjx6MxHva47YUl+uh3cu8lN2XYLDJm2nVDVjWfgCZrTgmnHJK8lO4aw9gxgnKeDmVgMW/YjXDA=,iv:SChwaCgQzB+6bxNe0NUUMUYFKuYazfNkQrMWKmMX/xM=,tag:zW5FIJg7dZ77nMU1KcNpAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
