apiVersion: v1
data:
    tunnel-config.json: ENC[AES256_GCM,data:Tm/MRgFCd2SQiKCcF3eDAAXw49EHlszEfj0Vbxhn8HwThSM5j9Ud4EQJfLjfRJkHQheqA45dMM8uTgJHcP41TaydjvLQkheughiD3G6RyLtDiSHI8SwGSJfWzvHEg6tvgbBqBpcSbARZjQUztBo+oeiwH/UcuI3c2JcXOYE0x+IBc/6JfH4bb5wf01pJS38kQ+Pf9Hy0JlLNopudtsRwck5r0ciRop3u+HhGDD4g3SLANAF4Fpu7lcCrEdnygNzsCY9O3gjBYSX8cV27I0580kUtK7hWMiRGnhS2kofUwns=,iv:kzh8qPQ/8+doLxqRBYUDBt+TFOp/bpYwHxeLuWMZy2M=,tag:z9GJ50Qw/dpzHEIw9Rqyxw==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSlhzWTVJaWd5RHJrQlJq
            TnpQUjRxUWpkV3NIY3FGUlVSakw5MDRqMHdVCjZyYXZoNlJ1aGxaRGg0NlcwVVVi
            V2QzcEoxRUQ2Sk9VSHhUV3VxOVVnb28KLS0tIFRVWlY0ck9rTmExaWllaEgrOWNW
            eGZtY1Fzc21JNEhjV0ttOU14RVFkZ2MK1S/Jny1SCfmwFqr21IcsEDvDhDon0rxl
            O9XLEkKKh/sB9MDnq+mWmOMLJCb/7eSK9wCYkF/Elb6Ngpmo82jfrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T18:16:33Z"
    mac: ENC[AES256_GCM,data:oCh5KiJSRA/Y4kcgz5psltuBUm8kjjej+RV9lrvqTF2GQHkY6KY4Nqf0/qOqOk/YhV+urPn5Opo6neYL1qBBr+UlD4fYH7XP1iFyrVREBeeHY5Lu6b2aOh8sQgD9Ab43YmpE+MCNBxh376/c8cD4ugcdQ+t9xZdF99Pf0oOgbm4=,iv:IY56qOLnqI1Ef7gNHE1I4wqeVbmyFeVAF0+l+BCwQEI=,tag:Xtx5A7WCHWyakqdI4Tp+NA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
