# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:X2jqUP5iMDlww9XfVsBm1pBXxa8BfRkG6hChN7QHlTyDMYlDrw==,iv:Nrktt1alT3xakZobpxqdVd0xSIy36GTOWAaUrsUpNmo=,tag:Rcx443y7xHobQ54LX2lb2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1txdgzrxrdlugc5qp0vujlynm4s8llt52ex6ckda0dwe49pgq7ffqdadkjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ1RSMVZhZThYUUFXTDd0
            bXZFVURGZHUzRHJ3ajdIV1RNMks1c3R1emdvCk5rNnEzTEU5N1JRUVdQM3RlRUZE
            a0JpZzNXY2doYm04bUJSWXpYQTFaekkKLS0tIE9KZnVSL2xVQjNiOFAydFBQR3JY
            dnFDZlhBcXVHYm0wUlhnZ0dteWpEL0kKd1wWhDFlRuASV3MUc+RjKhdluE4mnOw8
            hAPMoofyUX3NFuVIbSOt4nE5ZPv8twxL2MVVsb+GrFqwxBSDBftNPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T05:50:19Z"
    mac: ENC[AES256_GCM,data:N1BpWhOC0FEP+Te7SL2E3BkZFj/6VZp1UFRiVx7GzBy8vxJI0IkD5XF7XVRqJArBvOgQzgZN6Ln9PldmXd3ef0FZrFqHfCE4FtoXO6C4zkA4/w62dKkvJk/+eYBtfGhb4tlC0gdEgKxjX5zo9myz0M9HV0fwlVJ9D+2lIIXbyVM=,iv:HC8bvbx1Qrai11thzUQ/QHAx8a6qBtqWPk7nQnOq/Fw=,tag:01TJ4z0qsywh3Ln9D5WIaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
