---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  annotations:
    secrets-migration.pik8s.dev/phase: dual-write
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: external-dns-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        api-token: '{{ index . "api-token" }}'
  dataFrom:
    - extract:
        key: external-dns-secret
