apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:a605uEp5fHfR6H9L0Uy+tb0d02lXxhVmk3XBgUpzoyWcDvcLpFjs8g==,iv:0p2Cs/9aYXvDBPNnd48esYPOycING5wY23k+b66IK2U=,tag:A10Q03ZmSq4c6l9q7bKg4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQW45Tit2WW04dGFSYUp5
            cEMxYmJqekNUZDNaYnB0K3hNYStJeWQybHhNCkd1SGY1TGxSbXd1ZUQyNCtibmgx
            ajNIZy80YWt6Q1BWejBlRHJpOWcwdEUKLS0tIGJiN1gwN3hKOGNybXR3Ym1EcjQw
            MVp6UWNvQmF6V1owSFhoZTNaTzRCT0kKfH3NzN/hjUZ/+t6mNk7lsLJkc9T/6C8A
            1QjbOZZ+ZO7B3uiMwE63uZ5K8MmC/z+aOCJ3vWXA6EyB1889bFI52w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T20:16:25Z"
    mac: ENC[AES256_GCM,data:gn459Jo9S8M1Z0h0thuQ5Ee4i8KMftTYt88sQp9XzXdW5+c1EwZ2KAnbsvgi8M5qYaDN/GFWtyPWua750v5V336FtOGDyuKO7yIv3l0F8iXKFkicwydN1bAIcOKtmLLFxGUnCcS9d4bCPPw63ptGJxnabuH/7V5fmR2FCQ5+7ic=,iv:V/8+RhTy2AbryJITcbnj5PFBLB6pvg8stKpTNaOSiSI=,tag:9dl8PV5DG6ih2CjtMSpE4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
