apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+uflNiuWJ0n5sxcnYh3e8wQSntONLXLRW/qOh0PAatKoSgwBRegdoQ==,iv:KL5P+7RcZbGw+y4H5x1hJrOK4ot5jZj+MM10ZnuQrRY=,tag:w7NmeFCANbONFSni4K8upg==,type:str]
sops:
    age:
        - recipient: age13tgynpy3lm785sydz78hxx5dlqp85g25an4tmekx5l99fdzzns0qd89t25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVkvenpVS1pMQWRuUTNJ
            c0NkMUMxbWhkandIeDMvb0FNcVdEV1RiS2hnCjlvTW90RHZpRytGV3dkVEFUQ0Iv
            WHN1UHNUck91VFhjR1hJcWRJZW9UOVkKLS0tIGZUbXhkZ3RuNlZsUU9jRGVOaTJX
            YmhLakd5OENFVHFNSHFGWERDUThjODQKdh/diL6MNBmteBJEpUJ2QRM4XhA9pGcq
            fuVRs/TkU8wCNvj8r9b2GhuMOCFgADvehQGu3aBpYdMCU+7Awx7BGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T01:58:22Z"
    mac: ENC[AES256_GCM,data:B9fH8qigIz3Jr+mXPd3LZZCCJ91Nzch41/Whet6DfNL4ogcIr1NGaGSswMBhi3C7I58H6rSJwDiVQcrGw1VjuEwnoE7oiMT5jRYx0D7tiySDLBkb7DNLg3oMQZpEK6G+CkzSerqR6LytYkzXoMmmFe8mF1qDJbEQVLq4GSKWqpY=,iv:UhGwL1vi7zKP7CxTlxWzyQWcQrQHWzaKwjShWmJLcfw=,tag:818VULz5uzOXOfPCpVfxKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
