apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Q/oaHi2XZY/x72sBWbxEw9QWAjxxSppGImP+LNDFQle6aYXy1Nh4rg==,iv:t7Bl/vb4dDciptWLbdD3AGvDDRaO5cz9ShnLEBMSF+g=,tag:un9d+t/BTGTP2OpnZpffvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbUIxMUkyeG13UGx4bHZG
            RTZERzJ1bHNsalRjS2J0ZlFCRUN0dElHYWt3ClhBaHFRWkJYdzV0aGxhS3Btem1v
            dUhOZDF3QjUwU01vQVB6eGdPK2dvaEEKLS0tIERHZ1RIU0FGV0k0TkM1K1VRcjdn
            SU1ySjBkMGFEZXBzZ0RzemdCbzNuSEEKcxYNSqgnnBirvYKTtpq3NsVk4e3TQ8Du
            JNYOcRuPyZpSM/YBRcUSVkPjL7LQUz4uyG1il6UHC6V0QZH/s4LTjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T01:57:25Z"
    mac: ENC[AES256_GCM,data:4UF/L8z5449bj58xXwHM/+KMYNS1A9a3d+rPKZ4z9mZ3oBVc+LciCYp5nNrYWQJYkvQ1y/QJvaTRnHvunKLBGNAI7q3SlQ47BplLS0GbqW1ehD3rK4j9SS1u265tZkr5SntLned6JXEY5ynOi3WK70sH/+QHKl6/HNXMZH3YQU4=,iv:mKDAxoDo78cTWG/6TDpKKZ4flYoPzwZTDu8b110FOqc=,tag:rO7FpRAquIEsNsb4eghEPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
