apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:mu4tW9vZC/qNRxlqIzmu7ggwnu9Apw09aC7Q664UKWPySebEwArVMw==,iv:vBf8k3rp9HzIDH1QI+tLlZj+VD7s1prwWGg0p5oyEuw=,tag:OXCv9uPkxFELzHZHqTA33w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS0xqdExJazA0dk9IeUR6
            YzQwd0NrT2JwY1ZNZGhzUjhDUEc2VWkzd0FjClJ6bUZJL1phVWZRNlFJWnVJRlpK
            RmtEZ3FmUGFUTFp4R3JOOEZSZWN1a1kKLS0tIHNOdDBnUWZQRE1mSDNKb1dLYm04
            bWNhMmxpMG81MnVMRFRmdUlvNzZRRFUK9IcVkctmj3nz/Qvg2mqNE2WwuvtLiV3m
            aFtaccouQvFn1anYAaJUpSbDb0DhOxrP9kAEFyJibv8+DWywMmePiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T17:03:14Z"
    mac: ENC[AES256_GCM,data:rZM2EtiAk7/BamM/5UL7hx8KUJJJ9+F6KDZ61QY42+6AxDX1hSleyPGvpX+TNxXj4esYdwFQ6Dteq/b203EhxRuVg7zwLXB3qsev5VV0sHRN6O97sOfDUCMtOHt7xdNHE8+0/ygvqJf71cI8RfyFn09RNGRNgUT+Pw7WVFE58eI=,iv:Hm2nviEfPWw2tk5DFS9mgJIKA9bsE4eSXf0SwvMPnoU=,tag:l9yYoTmQzJPuXetRYWYN4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
