apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:8VvTXH+27b+z7bW2tXjxepF31VCETm6m6GNH6gw3f60Re0xUCQ6Rsg==,iv:g1Xqm7QnWv3he9meJo8cweQSa0q+NLuXF1Mw2NfndRA=,tag:M3aUilr0a/Bllo+hoB9sng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1epzwhsd46ezg2h7fdkqq3sexwk2v5re8smauah0f9hhug96d7pyqajt4ds
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydTZ6TTlJU1RON2c2M25m
            WXNqYXhhYk4vQm9zVVNTcW9UT1lyY0lRNDNZClE2N0NoRVVicjRRM05jMFBKTnJm
            RGh3VFhTM2tPbC9XMDQxUHpleXp6eGcKLS0tIHJIMk0wQ1JXSElrK2F4VStJLysx
            QlI0bjJlTmZ4R1Q3SkhaY2I0T1Vyd3cKtFawhgMP3Z41fU65sj1u2/csYJ31NypI
            +jfLhx0R2rSWcmLUPCbiIiqqIA3v1bPhimLLs1kdQiqDfotW1Ys/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:41:54Z"
    mac: ENC[AES256_GCM,data:ItE77CSPfXkqEHvUzhJnpFdLQ1JKKjmHE04gq2kg8EjO4G+kxAz+y06wnLgj5Jn7TZmIefQRH+HO5NSxJQLa0epNJs+UT4TksS15gvE8ryr4gFaWalGzO31A09GU1+ZgCM5x5ZyaDn6L/BjerRX9kaRdHyW8BWGP2reEmUHXAOA=,iv:v8gsKTLoZ7UorJHXwkquEikt7ZdVVeInTjHimsyu1fc=,tag:btq5rvdF7nVfiAVrKq3wrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
