apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:KinAe1Q9I6ewdHresyDHAA2Zny3JckMe8jhbqV/mfsZm4BAexps23Q==,iv:3W2Ef2Lq0rQjY7Plx+EiIJ7GYdbxDZRQN0BxUOXUimo=,tag:S7FNMm6shAdU6LI9D8f3Vg==,type:str]
sops:
    age:
        - recipient: age13tgynpy3lm785sydz78hxx5dlqp85g25an4tmekx5l99fdzzns0qd89t25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzkyNVkwSGRGVEdTMVR4
            MVZTeEo0d2hTNDBsMnB3amcxL1JIR3E0ZEU0ClIzdEpRTk02bVEyYVNncDhTRWR5
            YUd1S0Z5RDZ6bnpPTmRoWmM5aHF2bXcKLS0tIHExOEVLYXAyV2lXazR2Y1J5ZVEx
            blZYYU5uRXJvQmxJWGQrWUo3aWNoV2sKvNHZQUY+DmgWAh0HpFtOHojNjluoweEg
            9URp8Tl+k2j+33+MMDuSVNJvhJOV18y/RxWbDmyWxxCOAW+1DmPfGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T23:56:46Z"
    mac: ENC[AES256_GCM,data:0jQHioYR4Ur4PRapbKUOlnRV3+sUNqCuynmPY2eDZUEljVzVPI3/CCr066KKaNs68rGB1XMANpH9uaDMxtpSbSrgSLUCVSvRgH1yaCFZ3xN0GAAT3uzntYpglwPtWQwn6AeoOWh5ROnxJpnoLd3HEc7TUZ1LKtgisIdUUGHZHvM=,iv:cWXfebYFgitchTMIjoxE6iKs4re8zsxGV9h+XtVNSM8=,tag:a3XasQFThZt/+m3lB15VPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
