apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tpA1peZi1b+8RIVzJJz0u0PmDsn9suwJQo0MRGM4MBtFw3hkkY14Og==,iv:weS7RLcWkogjyERjh0DJ/d958y4148WxV5GLXGXqcl0=,tag:cuP1M/OsoVI0PGg9Ni8CnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUGxaZmM3dnN6aXdkREtl
            V3RRUkVEdFFYU21QSmpobWh5b1BpdDZaVlRJCnFoNnErOTdlMWtQa0xoOThkellH
            d0p6blVOOE5vU0xFNG11a3U2ZVJvQ3cKLS0tIDJoN3lucEc0WlF6V1RqdGplOXU3
            eXdkK0VSaEJHbE9TRWtXUFhmc1hKdjAK+WYXeHkeCI4Q6WoB0BiDLF99IdHx0ASq
            yFOaIeHiPR1HxrcXCQE/+B/1DL6Ihj9kSY4ZkxPS1ektZZZaE7eVrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T16:52:43Z"
    mac: ENC[AES256_GCM,data:Ujqc2pGHPyDphKCAB8AFCOLwi/Q0engIHhYS25ow6uEZZOadUiD2fCpQ69OfIw3utxFz0ItUC+HcmuD/8LaYurxEdxG3zCwlQcEKEJEwMM2HSFZbd+Um1yJirX9ZvDJS6Fu4O1hnDRUoRznBESQbZqoQe/JmrpP1nhyQ7exSbxs=,iv:k7ado58qsZfddwsQjxdnu8REEROezKJR99tB3pq795I=,tag:bfMWfWenfbCL6vH7idB7CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
