apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:6zkk8uvlDkJK8MikeiYzCCvgYbQry1KXrGsEa3IAjIRaZOAbZxMzrQ==,iv:Wa6Ck/i/9oBSzXY9LFKOiYCdvNge9sTOjj9ezSJwYU0=,tag:cPxWe4Egb/d4+6TPSDPg0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hdtw306drrkxw3t74w8adz0y9rqy7c9ralkcql7yz5773pp7wahsqg98rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcmkvTGovdDJnekJkS21K
            b1pFS29MeVcvMGwvSGtwblBjNk9McUhNZ1d3CklRZEY3bTAzdWVTenZzb1ZlTUl5
            M0g2SWIvaFNFYTNwbGhoVS8xVVJjd1UKLS0tIHlNRHNQazZlWHc1NDdGSk01NkhR
            QlFHeDhpOEcxNG53aDQ2d1JMYmZQRWMKND85sMsG5AY8l1bHZ0fx8T+VsA7vf0OP
            zVQdQPZu2pc7lKLW1OWh+x4AcixtTwlzSIMfPOqam7YJhRCpi6JKLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T16:01:10Z"
    mac: ENC[AES256_GCM,data:8aCR+4bCJrseRmlJM/8Vyf8AK97M5Fx7IjLSJ3TSUq41m+PBNS1Ik2q+Y61hLmU1tKXhzlcxnNDP7942HVNYnufJoNWCWlApoLVw4K0E/zVJujVEIKXyBaORW2v60f0RN+QU04ledyoXMHBGX9kHAXX2NkwIPyZMjkcnkYZbkXM=,iv:2kL+eYHYMzc9wuNduYFPrtYGWyDKvsTSCK27Osf1Gus=,tag:5TAr+dqHh/oEFxuQk6yiXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
