---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  K3S_CHANNEL: "https://update.k3s.io/v1-release/channels/stable"
  ZFS_ADDRESS: 192.168.6.5
  NFS_ADDRESS: 192.168.6.5
  NFS_USER_ID: "2000"
  NFS_GROUP_ID: "2000"
  NFS_MEDIA_PATH: /pool-01/
  TIMEZONE: "America/Chicago"
