---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "OpenTofu Apply"

on:
  push:
    branches: ["main"]
    paths: ["terraform/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apply:
    name: OpenTofu Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        directory: 
          - terraform/cloudflare
    env:
      # Cloudflare R2 backend configuration
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Cloudflare provider variables
      TF_VAR_cloudflare_r2_api_token: ${{ secrets.CLOUDFLARE_R2_API_TOKEN }}
      TF_VAR_cloudflare_r2_account_id: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OpenTofu Apply
        uses: dflook/tofu-apply@v2
        with:
          path: ${{ matrix.directory }} 